import type { LevelPack } from '../types'

/**
 * Tug of War — Every balloon has a rival.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack9: LevelPack = {
  id: 'pack-9',
  name: 'Tug of War',
  tagline: 'Every balloon has a rival.',
  levels: [
    // 1 (global 193) — 5 of 9, 2 ways, 26 near-misses
    { weights: [-6, 25, -29, 92, 50, 30, -40, -42, 60] },
    // 2 (global 194) — 5 of 9, 2 ways, 26 near-misses
    { weights: [-30, -18, 20, -44, 88, 24, 25, 71, -13] },
    // 3 (global 195) — 5 of 10, 4 ways, 28 near-misses
    { weights: [96, -41, 48, 74, 15, -5, -15, 96, -4, 21] },
    // 4 (global 196) — 5 of 9, 1 way, 23 near-misses
    { weights: [25, 36, 88, -17, -36, -26, -14, 89, 12] },
    // 5 (global 197) — 4 of 9, 4 ways, 34 near-misses
    { weights: [-14, 18, 24, -6, -6, -34, 46, 10, 61] },
    // 6 (global 198) — 5 of 9, 2 ways, 24 near-misses
    { weights: [68, -39, 89, -34, -30, -6, -19, 91, 32] },
    // 7 (global 199) — 4 of 9, 1 way, 25 near-misses
    { weights: [-13, -10, -32, -18, 91, 78, 15, -15, 94] },
    // 8 (global 200) — 5 of 9, 3 ways, 30 near-misses
    { weights: [63, -19, 66, -29, -14, 38, 16, -30, 46] },
    // 9 (global 201) — 5 of 9, 3 ways, 30 near-misses
    { weights: [-9, 6, 29, -11, -5, 19, 69, -11, 15] },
    // 10 (global 202) — 5 of 9, 2 ways, 27 near-misses
    { weights: [-41, -35, 7, 77, -16, 80, 77, 43, -14] },
    // 11 (global 203) — 5 of 9, 2 ways, 27 near-misses
    { weights: [41, -19, -13, 79, -28, 64, -21, 32, 12] },
    // 12 (global 204) — 5 of 9, 3 ways, 28 near-misses
    { weights: [-25, -13, 71, -16, 45, 44, -19, 8, -10] },
    // 13 (global 205) — 5 of 9, 2 ways, 25 near-misses
    { weights: [-7, 72, 8, -8, 69, -30, -22, -42, 55] },
    // 14 (global 206) — 5 of 9, 1 way, 27 near-misses
    { weights: [11, 47, -19, 22, -16, 26, 87, -32, 11] },
    // 15 (global 207) — 5 of 9, 2 ways, 23 near-misses
    { weights: [-12, -11, -24, 84, -16, 74, 45, -21, -26] },
    // 16 (global 208) — 5 of 9, 2 ways, 28 near-misses
    { weights: [74, -16, -22, 40, -9, -29, 30, 54, 23] },
    // 17 (global 209) — 5 of 9, 2 ways, 28 near-misses
    { weights: [66, 38, -43, 93, -36, -5, 66, -44, 46] },
    // 18 (global 210) — 5 of 9, 2 ways, 28 near-misses
    { weights: [31, -10, 33, -6, 12, 66, -16, 41, -45] },
    // 19 (global 211) — 5 of 10, 3 ways, 30 near-misses
    { weights: [-34, 97, -42, 80, 6, 50, 80, -37, -39, 32] },
    // 20 (global 212) — 5 of 9, 3 ways, 29 near-misses
    { weights: [-18, 99, 28, -25, -17, 89, -13, -30, 12] },
    // 21 (global 213) — 5 of 9, 2 ways, 26 near-misses
    { weights: [84, -38, -46, -16, -16, 27, 64, 58, -27] },
    // 22 (global 214) — 5 of 9, 2 ways, 26 near-misses
    { weights: [62, 71, -21, -41, -41, -28, 98, 39, -40] },
    // 23 (global 215) — 5 of 9, 1 way, 23 near-misses
    { weights: [37, 81, -37, -41, -25, 53, -19, -5, 50] },
    // 24 (global 216) — 5 of 9, 1 way, 28 near-misses
    { weights: [98, 85, 57, -5, -34, -40, 6, 11, 48] },
  ],
}
