import type { LevelPack } from '../types'

/**
 * Fine Margins — Everything lands one off.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack8: LevelPack = {
  id: 'pack-8',
  name: 'Fine Margins',
  tagline: 'Everything lands one off.',
  levels: [
    // 1 (global 169) — 5 of 10, 2 ways, 24 near-misses
    { weights: [96, 93, 57, 39, -36, -24, -36, 61, 35, -4], maxWeights: 5 },
    // 2 (global 170) — 5 of 10, 4 ways, 32 near-misses
    { weights: [92, -15, -16, -30, -38, 46, -18, 95, -45, -21] },
    // 3 (global 171) — 5 of 10, 1 way, 27 near-misses
    { weights: [-20, 72, -35, 9, -41, 9, 95, 95, 35, 91] },
    // 4 (global 172) — 5 of 10, 1 way, 38 near-misses
    { weights: [-6, 57, -42, -22, 31, 61, 20, 46, 56, -22], maxWeights: 5 },
    // 5 (global 173) — 5 of 10, 3 ways, 30 near-misses
    { weights: [59, 20, 92, 71, 70, -35, 81, -40, -41, -20] },
    // 6 (global 174) — 5 of 10, 3 ways, 27 near-misses
    { weights: [-36, 16, 83, 80, -40, -33, 19, 82, -22, -33], maxWeights: 5 },
    // 7 (global 175) — 5 of 10, 3 ways, 35 near-misses
    { weights: [-22, 65, -6, -28, 57, -24, -18, 68, 53, 72], maxWeights: 5 },
    // 8 (global 176) — 5 of 10, 4 ways, 43 near-misses
    { weights: [-25, -13, 68, -42, 20, 71, 35, -18, 84, -7] },
    // 9 (global 177) — 5 of 10, 2 ways, 42 near-misses
    { weights: [85, -16, -39, -28, 19, 94, 61, -25, -38, 24] },
    // 10 (global 178) — 5 of 10, 2 ways, 24 near-misses
    { weights: [-43, 64, 77, 70, -13, -19, -23, -28, -25, -32], locked: [1] },
    // 11 (global 179) — 5 of 10, 2 ways, 45 near-misses
    { weights: [46, -40, -5, 96, 25, 65, 64, -45, -8, -6] },
    // 12 (global 180) — 5 of 10, 1 way, 25 near-misses
    { weights: [53, 98, 75, 87, -27, -42, 65, 75, -35, -27] },
    // 13 (global 181) — 5 of 10, 4 ways, 49 near-misses
    { weights: [-11, 22, 14, 94, 27, 81, -22, -31, -45, -8] },
    // 14 (global 182) — 5 of 10, 3 ways, 32 near-misses
    { weights: [52, -23, 42, -38, -20, 13, 81, -23, 88, 93] },
    // 15 (global 183) — 5 of 10, 1 way, 24 near-misses
    { weights: [-26, 20, 49, -6, 28, 13, 91, 81, -5, 82] },
    // 16 (global 184) — 5 of 10, 2 ways, 26 near-misses
    { weights: [79, -30, 15, -14, 61, 25, 85, -31, 61, -35], maxWeights: 5 },
    // 17 (global 185) — 5 of 10, 1 way, 38 near-misses
    { weights: [57, -28, 42, 57, -11, 11, 65, 43, 31, -8] },
    // 18 (global 186) — 5 of 10, 3 ways, 37 near-misses
    { weights: [84, -15, -19, -24, -40, 55, 87, 70, 53, -36] },
    // 19 (global 187) — 5 of 10, 1 way, 36 near-misses
    { weights: [-23, 64, -7, -4, 44, 24, 8, 93, 51, 17] },
    // 20 (global 188) — 5 of 10, 1 way, 39 near-misses
    { weights: [35, 41, -16, -19, -19, -22, 8, 30, 92, 68], maxWeights: 5 },
    // 21 (global 189) — 5 of 10, 3 ways, 24 near-misses
    { weights: [82, 35, 43, 85, -38, -30, -40, 93, 51, -30], maxWeights: 5 },
    // 22 (global 190) — 5 of 10, 4 ways, 40 near-misses
    { weights: [-33, -8, 74, 27, -19, -8, 62, 77, -12, 18] },
    // 23 (global 191) — 5 of 10, 3 ways, 25 near-misses
    { weights: [71, -33, 34, -34, -11, 52, -34, 50, 93, 53], maxWeights: 5 },
    // 24 (global 192) — 5 of 10, 2 ways, 29 near-misses
    { weights: [-42, -8, -44, 42, 19, 85, 76, 85, -34, 20] },
  ],
}
