import type { LevelPack } from '../types'

/**
 * Grandmaster — Every piece has to earn its place.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack12: LevelPack = {
  id: 'pack-12',
  name: 'Grandmaster',
  tagline: 'Every piece has to earn its place.',
  levels: [
    // 1 (global 265) — 6 of 11, 1 way, 32 near-misses
    { weights: [-4, 91, 87, 65, -23, 37, -22, -22, 37, 40, 73], maxWeights: 6 },
    // 2 (global 266) — 6 of 11, 4 ways, 29 near-misses
    { weights: [86, 30, 46, -38, 86, 95, -12, 65, 65, -22, -12] },
    // 3 (global 267) — 6 of 11, 3 ways, 28 near-misses
    { weights: [30, -37, 46, -42, -24, 43, 88, 23, 95, 92, -17], locked: [10] },
    // 4 (global 268) — 6 of 11, 2 ways, 30 near-misses
    { weights: [-8, -28, -27, 71, 70, -11, 71, 80, 81, 46, 11], maxWeights: 6 },
    // 5 (global 269) — 6 of 11, 3 ways, 76 near-misses
    { weights: [57, -5, -25, -32, -28, 98, 46, 55, -7, 71, -21], maxWeights: 6 },
    // 6 (global 270) — 6 of 11, 2 ways, 58 near-misses
    { weights: [78, -13, -34, 19, -23, 72, 72, 85, 81, -46, -13] },
    // 7 (global 271) — 6 of 11, 3 ways, 83 near-misses
    { weights: [-11, -30, 20, -38, -36, -17, 99, -7, 66, 20, -10] },
    // 8 (global 272) — 6 of 12, 4 ways, 62 near-misses
    { weights: [-29, -18, -36, 99, -40, -5, -22, 39, -29, 43, -25, 74], locked: [2] },
    // 9 (global 273) — 6 of 12, 3 ways, 43 near-misses
    { weights: [45, 79, -14, -42, 68, 58, 92, -5, 71, 68, 29, -9] },
    // 10 (global 274) — 6 of 12, 2 ways, 53 near-misses
    { weights: [84, -37, -39, -24, 96, -13, 69, 49, 86, -43, 82, 88], maxWeights: 6 },
    // 11 (global 275) — 6 of 12, 3 ways, 86 near-misses
    { weights: [74, -4, -13, -8, -32, -25, -25, -4, 55, 36, -34, 95], locked: [6] },
    // 12 (global 276) — 6 of 12, 3 ways, 29 near-misses
    { weights: [-12, 86, -12, -45, 13, -39, -29, 30, -41, -5, -13, 86], locked: [0], maxWeights: 6 },
    // 13 (global 277) — 6 of 12, 4 ways, 60 near-misses
    { weights: [-35, 66, -33, 88, 19, 22, 84, 84, -13, 57, -24, 86] },
    // 14 (global 278) — 6 of 12, 4 ways, 105 near-misses
    { weights: [-28, 96, 90, 68, -15, 68, -24, -15, -38, 92, -28, -34], maxWeights: 6 },
    // 15 (global 279) — 6 of 12, 1 way, 46 near-misses
    { weights: [29, -19, 7, 84, -22, 75, -13, -32, 48, -35, -6, 6], locked: [1], maxWeights: 6 },
    // 16 (global 280) — 6 of 12, 4 ways, 96 near-misses
    { weights: [-35, 97, 19, -37, 90, 39, 11, -11, -11, -33, -24, 86], maxWeights: 6 },
    // 17 (global 281) — 6 of 12, 5 ways, 58 near-misses
    { weights: [95, -16, -23, 57, 95, -43, -39, -45, -32, 41, -29, -32], locked: [2] },
    // 18 (global 282) — 6 of 12, 4 ways, 49 near-misses
    { weights: [-34, 86, -7, -8, -33, 37, 53, 26, -34, -13, 16, -17], locked: [7], maxWeights: 6 },
    // 19 (global 283) — 6 of 12, 4 ways, 75 near-misses
    { weights: [84, 84, 58, -18, 92, -29, -29, -40, -11, -27, 92, 95] },
    // 20 (global 284) — 6 of 12, 2 ways, 37 near-misses
    { weights: [12, -44, 96, 70, 75, 96, -6, 93, -37, -11, -43, 68], locked: [1], maxWeights: 6 },
    // 21 (global 285) — 6 of 12, 5 ways, 78 near-misses
    { weights: [-27, -27, 32, 93, 76, 85, -39, -27, 42, 23, 97, -13], maxWeights: 6 },
    // 22 (global 286) — 6 of 12, 1 way, 26 near-misses
    { weights: [87, -9, 81, 68, 78, -15, -25, -37, 83, 62, -18, 71], locked: [1], maxWeights: 6 },
    // 23 (global 287) — 6 of 12, 5 ways, 43 near-misses
    { weights: [-8, -29, 8, 95, 87, -38, 95, 92, 90, -35, -10, 93] },
    // 24 (global 288) — 6 of 12, 3 ways, 47 near-misses
    { weights: [84, -21, 59, 82, -37, -35, 74, -6, 74, 32, 58, 92] },
  ],
}
