import type { LevelPack } from '../types'

/**
 * The Gauntlet — Twelve last words.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack13: LevelPack = {
  id: 'pack-13',
  name: 'The Gauntlet',
  tagline: 'Twelve last words.',
  levels: [
    // 1 (global 289) — 6 of 12, 2 ways, 32 near-misses
    { weights: [48, -39, 91, 85, 64, -12, -13, 69, -13, -17, 26, -34], locked: [6], maxWeights: 6 },
    // 2 (global 290) — 6 of 12, 3 ways, 35 near-misses
    { weights: [-6, 81, 87, 87, -32, 53, -36, 70, 32, -9, -30, -27], locked: [4], maxWeights: 6 },
    // 3 (global 291) — 6 of 12, 2 ways, 32 near-misses
    { weights: [-21, 91, 82, 81, 82, 28, 64, -12, -32, 85, 90, -41], maxWeights: 6 },
    // 4 (global 292) — 6 of 12, 2 ways, 90 near-misses
    { weights: [91, 92, -35, 56, 87, -33, 78, 54, -28, -14, -14, -26], maxWeights: 6 },
    // 5 (global 293) — 6 of 12, 4 ways, 35 near-misses
    { weights: [94, -39, 96, 84, -45, -31, 89, -31, 92, 92, -26, -31], locked: [11] },
    // 6 (global 294) — 6 of 12, 3 ways, 53 near-misses
    { weights: [71, 57, -27, 50, 48, 91, 40, -15, -36, 93, -5, 62] },
    // 7 (global 295) — 6 of 12, 2 ways, 35 near-misses
    { weights: [95, -12, -30, -21, -21, 51, -4, 75, 91, -39, 12, -18], locked: [7], maxWeights: 6 },
    // 8 (global 296) — 6 of 12, 2 ways, 42 near-misses
    { weights: [-39, 77, 23, 81, 42, -31, -39, -11, -18, 97, 77, -20], locked: [6], maxWeights: 6 },
    // 9 (global 297) — 6 of 12, 2 ways, 44 near-misses
    { weights: [99, 50, 63, 89, 95, 43, -14, -31, 89, -24, 25, -6], maxWeights: 6 },
    // 10 (global 298) — 6 of 12, 2 ways, 32 near-misses
    { weights: [-33, 83, 75, 91, -14, 79, 11, -41, 37, 95, -22, -22], locked: [10], maxWeights: 6 },
    // 11 (global 299) — 6 of 12, 2 ways, 64 near-misses
    { weights: [99, 83, -14, 39, 83, -39, 60, -17, -5, 82, 52, -34], maxWeights: 6 },
    // 12 (global 300) — 6 of 12, 5 ways, 89 near-misses
    { weights: [-18, -41, -7, -32, 80, -33, 71, 11, 80, 66, 94, -18], maxWeights: 6 },
  ],
}
