import type { LevelPack } from '../types'

/**
 * Sky High — Overshoot on purpose. Come back clean.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack6: LevelPack = {
  id: 'pack-6',
  name: 'Sky High',
  tagline: 'Overshoot on purpose. Come back clean.',
  levels: [
    // 1 (global 121) — 4 of 9, 4 ways, 23 near-misses
    { weights: [33, -21, 10, -29, -19, -26, 15, 28, 84] },
    // 2 (global 122) — 4 of 9, 3 ways, 26 near-misses
    { weights: [27, -10, 13, -44, 23, -9, 83, 24, 62] },
    // 3 (global 123) — 4 of 8, 3 ways, 25 near-misses
    { weights: [-9, -4, -11, 45, 29, -10, 6, 43] },
    // 4 (global 124) — 4 of 8, 1 way, 21 near-misses
    { weights: [8, 26, 57, -17, -6, -8, 70, 11] },
    // 5 (global 125) — 4 of 8, 1 way, 21 near-misses
    { weights: [-9, -40, 38, -4, 77, 81, 32, 42] },
    // 6 (global 126) — 4 of 8, 1 way, 21 near-misses
    { weights: [19, -24, 92, 87, -7, 6, 87, -17] },
    // 7 (global 127) — 4 of 8, 1 way, 21 near-misses
    { weights: [50, 9, 59, 48, -4, -7, -43, 66] },
    // 8 (global 128) — 4 of 9, 2 ways, 23 near-misses
    { weights: [7, 64, -23, -41, -8, 31, 85, 43, 40] },
    // 9 (global 129) — 4 of 8, 2 ways, 22 near-misses
    { weights: [6, 74, -8, 29, -21, 74, -5, -11] },
    // 10 (global 130) — 4 of 9, 3 ways, 24 near-misses
    { weights: [42, -15, -35, 42, -34, 41, 14, 75, -5] },
    // 11 (global 131) — 4 of 8, 1 way, 19 near-misses
    { weights: [51, 36, -23, -4, 37, 43, -24, -38] },
    // 12 (global 132) — 4 of 8, 1 way, 19 near-misses
    { weights: [-13, -34, 37, -35, 77, 34, -41, 34] },
    // 13 (global 133) — 4 of 8, 1 way, 19 near-misses
    { weights: [82, -20, 14, -18, 13, -8, 26, -12] },
    // 14 (global 134) — 4 of 9, 2 ways, 21 near-misses
    { weights: [-20, -31, 83, 59, -44, -4, 56, 6, 89] },
    // 15 (global 135) — 4 of 8, 2 ways, 20 near-misses
    { weights: [-12, -21, 84, 18, 16, -18, -16, -6] },
    // 16 (global 136) — 5 of 9, 3 ways, 23 near-misses
    { weights: [-15, 28, 45, 8, 17, 16, 97, -4, -28] },
    // 17 (global 137) — 4 of 8, 2 ways, 23 near-misses
    { weights: [69, 68, 69, -28, -37, -40, -33, 33] },
    // 18 (global 138) — 4 of 8, 2 ways, 23 near-misses
    { weights: [-6, -10, -6, -9, 31, 28, 52, 28] },
    // 19 (global 139) — 4 of 9, 4 ways, 25 near-misses
    { weights: [-23, 13, -5, 68, 46, 66, 17, -9, -8] },
    // 20 (global 140) — 4 of 9, 3 ways, 25 near-misses
    { weights: [-13, -38, -39, 31, 31, -7, 31, 81, 42] },
    // 21 (global 141) — 4 of 8, 1 way, 20 near-misses
    { weights: [57, 33, -20, -15, 70, -18, 14, -16] },
    // 22 (global 142) — 4 of 8, 1 way, 20 near-misses
    { weights: [70, 43, -32, 76, -4, -41, 72, -42] },
    // 23 (global 143) — 4 of 9, 2 ways, 22 near-misses
    { weights: [80, -18, -8, 20, -6, 76, 12, 48, -39] },
    // 24 (global 144) — 4 of 9, 2 ways, 22 near-misses
    { weights: [-8, 27, 45, 45, 83, 62, -37, -14, -36] },
  ],
}
