import type { LevelPack } from '../types'

/**
 * The Gauntlet — Nothing here is a gift.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack25: LevelPack = {
  id: 'pack-25',
  name: 'The Gauntlet',
  tagline: 'Nothing here is a gift.',
  levels: [
    // 1 (global 577) — 6 of 12, 6 ways, 64 near-misses
    { weights: [-30, -30, 99, 17, 17, -25, 99, -37, -43, -8, 22, -20], locked: [3], maxWeights: 7 },
    // 2 (global 578) — 7 of 11, 2 ways, 94 near-misses
    { weights: [34, -24, 11, 59, -12, -11, -24, -23, -17, 89, 65], maxWeights: 7 },
    // 3 (global 579) — 7 of 12, 3 ways, 77 near-misses
    { weights: [-8, 97, -8, 8, -16, 80, -27, -7, 95, 80, -26, -34], maxWeights: 7 },
    // 4 (global 580) — 7 of 12, 1 way, 55 near-misses
    { weights: [20, 99, -40, 58, 20, -9, -29, 93, 62, -38, -9, 40], locked: [5], maxWeights: 7 },
    // 5 (global 581) — 7 of 12, 3 ways, 135 near-misses
    { weights: [94, -28, -9, 14, -28, 94, -42, -9, 28, -28, -33, 21], maxWeights: 7 },
    // 6 (global 582) — 7 of 12, 4 ways, 133 near-misses
    { weights: [-21, 95, -21, -9, -24, -9, 68, 95, 9, -33, 30, -29], maxWeights: 7 },
    // 7 (global 583) — 7 of 12, 2 ways, 92 near-misses
    { weights: [-45, 95, -16, -25, -14, 93, 75, -25, -7, 95, 59, 30], maxWeights: 7 },
    // 8 (global 584) — 7 of 12, 2 ways, 89 near-misses
    { weights: [82, -11, -6, 6, -6, -11, -23, 71, 81, -19, 51, 82], maxWeights: 7 },
    // 9 (global 585) — 7 of 12, 1 way, 122 near-misses
    { weights: [-11, -34, 29, -27, 18, -18, 93, 91, -27, 63, 50, 61], maxWeights: 7 },
    // 10 (global 586) — 7 of 12, 1 way, 74 near-misses
    { weights: [68, -35, -20, 98, 56, 91, 89, -19, -34, 97, 20, -20], maxWeights: 7 },
    // 11 (global 587) — 7 of 11, 2 ways, 61 near-misses
    { weights: [-13, -24, -35, 93, -14, 74, 84, -35, -24, 73, -33], maxWeights: 7 },
    // 12 (global 588) — 7 of 12, 3 ways, 105 near-misses
    { weights: [91, -11, -25, 51, 95, -26, 95, -25, -34, -36, -44, -22], maxWeights: 7 },
    // 13 (global 589) — 7 of 12, 3 ways, 66 near-misses
    { weights: [-34, -16, -34, 92, 39, 98, -5, -34, 45, -34, -27, 68], locked: [0], maxWeights: 7 },
    // 14 (global 590) — 7 of 12, 2 ways, 100 near-misses
    { weights: [87, -32, 76, -39, 98, 87, -28, -13, -17, -32, 98, -11], maxWeights: 7 },
    // 15 (global 591) — 7 of 12, 4 ways, 59 near-misses
    { weights: [-21, -12, 84, -19, -13, 9, -36, -19, 93, -24, -25, -9], maxWeights: 7 },
    // 16 (global 592) — 7 of 12, 1 way, 88 near-misses
    { weights: [66, 94, -41, -44, -13, 59, 94, -30, 48, 77, -24, -13], maxWeights: 7 },
    // 17 (global 593) — 7 of 12, 1 way, 85 near-misses
    { weights: [47, 76, 69, 89, 76, 87, -4, -42, -26, -11, -40, -4], maxWeights: 7 },
    // 18 (global 594) — 7 of 12, 1 way, 80 near-misses
    { weights: [33, 78, 86, -8, 76, -12, -4, 68, -4, -13, -12, 39], maxWeights: 7 },
    // 19 (global 595) — 7 of 12, 2 ways, 68 near-misses
    { weights: [-42, 19, 42, -23, -14, -9, 96, 49, -37, 9, 96, -14], locked: [8], maxWeights: 7 },
    // 20 (global 596) — 7 of 11, 1 way, 56 near-misses
    { weights: [-22, 66, -22, -13, -11, 46, -22, -8, 68, -19, 74], locked: [0], maxWeights: 7 },
    // 21 (global 597) — 7 of 12, 2 ways, 127 near-misses
    { weights: [-43, -31, 27, -43, 41, -6, -27, 99, 99, -12, -29, -27], maxWeights: 7 },
    // 22 (global 598) — 7 of 12, 2 ways, 103 near-misses
    { weights: [-4, 93, -5, -9, -36, -42, -10, -24, -18, -46, 64, -9] },
    // 23 (global 599) — 7 of 12, 3 ways, 58 near-misses
    { weights: [-40, -6, -36, -11, -41, -30, -7, -26, 88, 14, 98, -33], locked: [8], maxWeights: 7 },
    // 24 (global 600) — 7 of 12, 1 way, 109 near-misses
    { weights: [16, -28, 32, -12, -21, -32, -4, -32, 97, -44, 94, -24], maxWeights: 7 },
  ],
}
