import type { LevelPack } from '../types'

/**
 * Last Light — The easy answers are gone.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack21: LevelPack = {
  id: 'pack-21',
  name: 'Last Light',
  tagline: 'The easy answers are gone.',
  levels: [
    // 1 (global 481) — 6 of 11, 3 ways, 51 near-misses
    { weights: [-22, -44, 78, 40, -38, 99, -33, -30, -25, 51, 94], maxWeights: 6 },
    // 2 (global 482) — 6 of 11, 1 way, 47 near-misses
    { weights: [63, -10, 88, -7, 97, 15, 48, -10, -40, -33, 90], maxWeights: 6 },
    // 3 (global 483) — 7 of 11, 4 ways, 47 near-misses
    { weights: [95, -10, 95, -10, -38, -23, 75, -14, 22, -37, 94], maxWeights: 7 },
    // 4 (global 484) — 6 of 11, 2 ways, 53 near-misses
    { weights: [96, 52, 73, -39, -30, -17, -16, 73, 30, 8, 82], maxWeights: 6 },
    // 5 (global 485) — 7 of 11, 1 way, 48 near-misses
    { weights: [66, -8, 80, 93, -14, 33, -25, -11, -6, 38, 91] },
    // 6 (global 486) — 7 of 11, 1 way, 43 near-misses
    { weights: [91, 36, -5, -16, 85, -16, 54, -31, 95, 74, -4], maxWeights: 7 },
    // 7 (global 487) — 7 of 12, 2 ways, 42 near-misses
    { weights: [-37, 90, 37, 70, -10, -27, -5, -36, 79, 42, 90, 92], locked: [5], maxWeights: 7 },
    // 8 (global 488) — 6 of 11, 3 ways, 71 near-misses
    { weights: [45, -26, -5, -27, 61, -15, -5, 13, 78, 70, 60] },
    // 9 (global 489) — 6 of 11, 3 ways, 60 near-misses
    { weights: [83, 82, -22, 42, -6, 57, -38, -17, 81, -31, 57] },
    // 10 (global 490) — 6 of 11, 4 ways, 53 near-misses
    { weights: [-32, 89, 61, -17, -12, -38, 91, -32, 17, 90, -26], maxWeights: 6 },
    // 11 (global 491) — 6 of 11, 3 ways, 53 near-misses
    { weights: [-43, 22, 66, 59, 99, -44, -18, 99, -26, -27, -12], maxWeights: 6 },
    // 12 (global 492) — 6 of 11, 1 way, 44 near-misses
    { weights: [-12, -30, 12, -9, 77, -39, 83, -34, -37, 16, -12], maxWeights: 6 },
    // 13 (global 493) — 6 of 11, 1 way, 49 near-misses
    { weights: [93, -30, -38, 76, -33, -33, 88, 63, -12, 90, 51], maxWeights: 6 },
    // 14 (global 494) — 7 of 12, 2 ways, 47 near-misses
    { weights: [75, 76, 75, -10, 86, -11, 34, 93, -44, -4, 84, -23], maxWeights: 7 },
    // 15 (global 495) — 7 of 12, 1 way, 44 near-misses
    { weights: [-18, -27, 90, 86, -18, -24, 78, -36, 95, 95, 90, 24], maxWeights: 7 },
    // 16 (global 496) — 7 of 11, 2 ways, 43 near-misses
    { weights: [45, -29, -16, 86, 37, -13, 24, -16, -13, 94, -42], locked: [3], maxWeights: 7 },
    // 17 (global 497) — 6 of 11, 3 ways, 54 near-misses
    { weights: [84, 11, -42, -41, 78, -9, 85, -10, -26, -41, 79], maxWeights: 6 },
    // 18 (global 498) — 6 of 11, 3 ways, 54 near-misses
    { weights: [-29, 32, 49, -37, 94, 94, -43, 95, -19, -26, -24], maxWeights: 6 },
    // 19 (global 499) — 7 of 11, 2 ways, 49 near-misses
    { weights: [-33, 94, -17, 98, -4, -37, 86, 9, -34, 93, 21], maxWeights: 7 },
    // 20 (global 500) — 7 of 12, 5 ways, 54 near-misses
    { weights: [84, -20, -13, -27, -13, 83, 79, -27, 95, 79, -23, 92] },
    // 21 (global 501) — 6 of 11, 3 ways, 74 near-misses
    { weights: [-38, 82, 26, -12, 85, -38, -4, -20, 28, 82, -13] },
    // 22 (global 502) — 6 of 11, 4 ways, 69 near-misses
    { weights: [-28, 6, -36, 85, -4, 98, 73, 77, -35, -35, -17] },
    // 23 (global 503) — 6 of 11, 4 ways, 71 near-misses
    { weights: [83, 68, -26, 94, -7, -11, -13, -13, 42, -13, 41] },
    // 24 (global 504) — 6 of 11, 3 ways, 74 near-misses
    { weights: [89, -30, -24, 14, -24, -11, -34, -46, 70, 50, 96] },
  ],
}
