import type { LevelPack } from '../types'

/**
 * Long Division — Break sixty-seven into pieces.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack17: LevelPack = {
  id: 'pack-17',
  name: 'Long Division',
  tagline: 'Break sixty-seven into pieces.',
  levels: [
    // 1 (global 385) — 6 of 10, 3 ways, 42 near-misses
    { weights: [-40, -5, 69, -15, 40, 96, -4, 62, -41, -40] },
    // 2 (global 386) — 6 of 10, 3 ways, 42 near-misses
    { weights: [-35, 78, 98, -23, 60, -7, 57, -17, -32, -35] },
    // 3 (global 387) — 6 of 11, 1 way, 39 near-misses
    { weights: [-13, 39, 23, -23, 62, -8, 55, 76, 70, 62, -20] },
    // 4 (global 388) — 6 of 11, 2 ways, 38 near-misses
    { weights: [43, 71, -37, 94, 46, -35, -19, 95, 88, -7, 11], maxWeights: 6 },
    // 5 (global 389) — 6 of 11, 3 ways, 39 near-misses
    { weights: [96, -30, -26, 25, 89, 76, -15, 94, -44, 55, -16], maxWeights: 6 },
    // 6 (global 390) — 6 of 11, 4 ways, 44 near-misses
    { weights: [79, -27, -5, 73, -10, 38, 74, 55, 68, -20, -4] },
    // 7 (global 391) — 6 of 11, 1 way, 35 near-misses
    { weights: [-40, -28, 47, 42, 84, 98, 96, 34, 90, -6, -41], maxWeights: 6 },
    // 8 (global 392) — 6 of 10, 1 way, 34 near-misses
    { weights: [-31, 23, 89, 54, -32, -8, -31, 80, -46, 46], maxWeights: 6 },
    // 9 (global 393) — 6 of 10, 1 way, 34 near-misses
    { weights: [-39, -5, -22, -27, -43, -46, 33, -28, 91, 90] },
    // 10 (global 394) — 6 of 11, 2 ways, 36 near-misses
    { weights: [64, -21, 99, 83, -40, 18, -42, -36, 56, -5, 76], maxWeights: 6 },
    // 11 (global 395) — 6 of 10, 2 ways, 40 near-misses
    { weights: [-26, -11, -31, 87, -39, -25, 8, 89, -33, 66] },
    // 12 (global 396) — 6 of 11, 2 ways, 38 near-misses
    { weights: [-33, -34, 19, -12, 84, 71, 26, 96, 26, -34, -19], locked: [0] },
    // 13 (global 397) — 6 of 11, 4 ways, 39 near-misses
    { weights: [90, -38, -46, -32, -28, 77, -36, 81, 33, 20, -8], locked: [5] },
    // 14 (global 398) — 6 of 10, 1 way, 37 near-misses
    { weights: [94, 99, 38, -37, -30, -38, 7, 21, 99, -26], maxWeights: 6 },
    // 15 (global 399) — 6 of 11, 2 ways, 44 near-misses
    { weights: [78, 28, 66, 94, 66, -16, 46, 12, -4, -5, -20] },
    // 16 (global 400) — 6 of 10, 2 ways, 38 near-misses
    { weights: [-37, 17, 64, 9, 16, -25, -27, -8, 89, -26], maxWeights: 6 },
    // 17 (global 401) — 6 of 10, 2 ways, 43 near-misses
    { weights: [-34, 17, 48, -13, -26, 96, -9, 61, -4, 48] },
    // 18 (global 402) — 6 of 10, 2 ways, 38 near-misses
    { weights: [-42, 27, -9, 36, 99, 79, 44, -15, -42, -10], maxWeights: 6 },
    // 19 (global 403) — 6 of 11, 4 ways, 40 near-misses
    { weights: [-42, -20, -23, -38, 99, 97, 94, -14, 75, -38, -35] },
    // 20 (global 404) — 6 of 11, 4 ways, 45 near-misses
    { weights: [56, -41, -5, 46, -21, 86, 56, -10, -8, 95, 86] },
    // 21 (global 405) — 6 of 10, 4 ways, 44 near-misses
    { weights: [-9, -30, -40, 99, 22, 71, -21, -35, 62, -20] },
    // 22 (global 406) — 6 of 10, 1 way, 40 near-misses
    { weights: [-22, -32, -10, 49, -11, 81, 87, 76, -43, 31] },
    // 23 (global 407) — 6 of 11, 2 ways, 40 near-misses
    { weights: [9, -13, 47, 99, 57, 68, 36, -6, -43, -6, 81], maxWeights: 6 },
    // 24 (global 408) — 6 of 10, 2 ways, 44 near-misses
    { weights: [76, -7, 52, -7, -29, 78, -24, 80, 43, -22] },
  ],
}
