import type { LevelPack } from '../types'

/**
 * Hairline — Miss by one, miss by a mile.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack12: LevelPack = {
  id: 'pack-12',
  name: 'Hairline',
  tagline: 'Miss by one, miss by a mile.',
  levels: [
    // 1 (global 265) — 5 of 9, 2 ways, 30 near-misses
    { weights: [-26, -6, 26, -44, -29, 71, 75, -36, 74] },
    // 2 (global 266) — 5 of 9, 1 way, 27 near-misses
    { weights: [-30, 47, 57, -34, 66, -9, 34, -13, -35] },
    // 3 (global 267) — 5 of 10, 3 ways, 30 near-misses
    { weights: [17, -38, 15, 85, 48, 83, 65, -38, -42, -25], maxWeights: 5 },
    // 4 (global 268) — 5 of 9, 1 way, 30 near-misses
    { weights: [-5, -5, 86, 53, 36, -36, 51, -12, 23] },
    // 5 (global 269) — 5 of 9, 1 way, 30 near-misses
    { weights: [37, -14, -40, 76, 16, 76, -35, -10, 11] },
    // 6 (global 270) — 5 of 9, 2 ways, 26 near-misses
    { weights: [58, 57, -29, 62, -12, 62, -22, -9, -22], maxWeights: 5 },
    // 7 (global 271) — 5 of 9, 2 ways, 31 near-misses
    { weights: [-22, 53, 39, 17, -34, 85, -16, -20, -33] },
    // 8 (global 272) — 5 of 10, 3 ways, 33 near-misses
    { weights: [43, 98, 86, -39, 27, -37, -29, -30, 75, -30] },
    // 9 (global 273) — 5 of 10, 4 ways, 33 near-misses
    { weights: [61, -24, 75, -14, -31, -40, 85, 41, 35, -24] },
    // 10 (global 274) — 5 of 9, 2 ways, 29 near-misses
    { weights: [-16, -32, 76, -16, 77, -26, -44, -11, 63] },
    // 11 (global 275) — 5 of 10, 3 ways, 31 near-misses
    { weights: [-26, -25, 12, 83, 7, -37, 89, 66, 11, -20], maxWeights: 5 },
    // 12 (global 276) — 5 of 10, 4 ways, 31 near-misses
    { weights: [-40, 27, -29, 73, -24, -41, 83, 36, -25, -36] },
    // 13 (global 277) — 5 of 10, 4 ways, 36 near-misses
    { weights: [-25, -26, 66, 31, 58, 71, 6, -20, -16, 68] },
    // 14 (global 278) — 5 of 10, 3 ways, 34 near-misses
    { weights: [45, 30, -14, 91, -6, -28, 99, 49, -35, -33] },
    // 15 (global 279) — 5 of 10, 3 ways, 34 near-misses
    { weights: [64, -41, 95, -39, -21, -32, 27, 21, 31, -40] },
    // 16 (global 280) — 5 of 9, 1 way, 29 near-misses
    { weights: [68, -4, -34, 97, -41, -28, -31, 69, 76] },
    // 17 (global 281) — 5 of 9, 1 way, 29 near-misses
    { weights: [66, -27, -23, -38, 53, 78, -10, -13, 61] },
    // 18 (global 282) — 5 of 10, 4 ways, 32 near-misses
    { weights: [80, 51, 60, -19, -37, 80, -10, -37, -22, -41] },
    // 19 (global 283) — 5 of 10, 4 ways, 32 near-misses
    { weights: [-46, -5, -34, -42, 10, 56, -24, 20, -26, 95] },
    // 20 (global 284) — 5 of 10, 3 ways, 35 near-misses
    { weights: [89, 87, -34, -13, -26, 61, -25, 21, 70, -29] },
    // 21 (global 285) — 5 of 9, 1 way, 25 near-misses
    { weights: [-43, -32, 85, 35, -11, -4, 77, 39, -9], maxWeights: 5 },
    // 22 (global 286) — 5 of 9, 1 way, 25 near-misses
    { weights: [-18, 40, 76, -16, -7, 71, -27, -27, 37], maxWeights: 5 },
    // 23 (global 287) — 5 of 10, 2 ways, 32 near-misses
    { weights: [72, -16, -24, 77, 96, 10, -9, 89, -35, -42] },
    // 24 (global 288) — 5 of 10, 4 ways, 33 near-misses
    { weights: [-13, -16, -37, -6, 93, -33, 76, 94, 78, -32] },
  ],
}
