import type { LevelPack } from '../types'

/**
 * Dead Reckoning — No landmarks. Just arithmetic.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack16: LevelPack = {
  id: 'pack-16',
  name: 'Dead Reckoning',
  tagline: 'No landmarks. Just arithmetic.',
  levels: [
    // 1 (global 361) — 5 of 10, 2 ways, 34 near-misses
    { weights: [84, -6, -10, 71, 30, -27, -38, -6, -21, 39], maxWeights: 5 },
    // 2 (global 362) — 6 of 10, 1 way, 34 near-misses
    { weights: [-13, 56, 76, -21, 94, 57, -13, -34, -7, 54] },
    // 3 (global 363) — 5 of 10, 3 ways, 45 near-misses
    { weights: [-17, 82, 39, -26, 39, 26, -27, -36, 73, -26] },
    // 4 (global 364) — 5 of 10, 4 ways, 45 near-misses
    { weights: [19, 47, 59, -34, 69, -25, -10, -26, 65, -44] },
    // 5 (global 365) — 6 of 11, 3 ways, 37 near-misses
    { weights: [-39, 44, 91, 80, 89, -16, 28, 85, -39, -10, 89], maxWeights: 6 },
    // 6 (global 366) — 6 of 10, 4 ways, 36 near-misses
    { weights: [-13, -24, 77, -34, -40, 83, -22, -18, 74, -25] },
    // 7 (global 367) — 6 of 10, 2 ways, 38 near-misses
    { weights: [34, -31, -7, 86, -33, -23, 88, 24, 75, -34] },
    // 8 (global 368) — 6 of 10, 1 way, 35 near-misses
    { weights: [-34, 75, -16, -28, 38, -37, -41, 58, 97, 89] },
    // 9 (global 369) — 5 of 10, 2 ways, 43 near-misses
    { weights: [70, 84, 79, -9, 48, -5, -13, -39, -11, 44] },
    // 10 (global 370) — 6 of 10, 1 way, 33 near-misses
    { weights: [-22, 60, -8, 92, 91, -37, 57, -11, -29, -32] },
    // 11 (global 371) — 6 of 10, 1 way, 33 near-misses
    { weights: [-43, -19, -22, 16, -41, 83, 93, 24, 99, 8], maxWeights: 6 },
    // 12 (global 372) — 6 of 11, 2 ways, 40 near-misses
    { weights: [-44, 20, 86, 77, 54, 55, -43, 93, -4, 53, -5] },
    // 13 (global 373) — 6 of 10, 2 ways, 39 near-misses
    { weights: [38, -44, 46, 72, -25, 95, -34, -10, -21, 32] },
    // 14 (global 374) — 6 of 10, 2 ways, 34 near-misses
    { weights: [-43, 57, -7, 61, 9, 92, -5, -31, -30, 92], maxWeights: 6 },
    // 15 (global 375) — 6 of 11, 4 ways, 38 near-misses
    { weights: [47, 9, -8, -41, -8, -32, 6, 44, 73, -5, 56], locked: [8] },
    // 16 (global 376) — 6 of 11, 3 ways, 42 near-misses
    { weights: [70, 31, 77, -11, 96, -31, 83, 55, -28, -14, -7] },
    // 17 (global 377) — 6 of 10, 3 ways, 41 near-misses
    { weights: [-18, -15, -21, -17, 6, 86, -30, -27, 62, 89] },
    // 18 (global 378) — 6 of 11, 4 ways, 45 near-misses
    { weights: [-36, 97, 63, 51, -24, 43, -36, 26, 97, 81, -31] },
    // 19 (global 379) — 6 of 11, 4 ways, 45 near-misses
    { weights: [97, 99, -43, -21, -29, 44, 75, -36, 30, 53, 55] },
    // 20 (global 380) — 6 of 10, 4 ways, 44 near-misses
    { weights: [23, -9, 21, -20, -32, 63, 90, -18, 60, -25] },
    // 21 (global 381) — 6 of 10, 3 ways, 39 near-misses
    { weights: [95, 15, -6, 51, 61, 24, -21, -13, -41, -14], maxWeights: 6 },
    // 22 (global 382) — 6 of 10, 1 way, 35 near-misses
    { weights: [25, -7, -41, 57, 93, 16, 95, 24, -33, -40], maxWeights: 6 },
    // 23 (global 383) — 6 of 11, 3 ways, 37 near-misses
    { weights: [-17, 56, -31, 60, -16, -28, -23, 91, -11, 25, 88], locked: [4] },
    // 24 (global 384) — 6 of 10, 3 ways, 37 near-misses
    { weights: [-21, 78, 55, 15, -24, -16, -24, 78, -28, -24], maxWeights: 6 },
  ],
}
