import type { LevelPack } from '../types'

/**
 * No Margin — Exactly, or not at all.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack22: LevelPack = {
  id: 'pack-22',
  name: 'No Margin',
  tagline: 'Exactly, or not at all.',
  levels: [
    // 1 (global 505) — 6 of 11, 2 ways, 57 near-misses
    { weights: [-6, -19, 13, 61, 66, 45, -29, 29, 48, 87, -32], maxWeights: 6 },
    // 2 (global 506) — 7 of 11, 1 way, 42 near-misses
    { weights: [-36, -12, -19, -20, -25, -7, 97, 96, -27, 97, 88], maxWeights: 7 },
    // 3 (global 507) — 6 of 10, 2 ways, 56 near-misses
    { weights: [-18, -24, -28, 64, -19, -18, -40, 42, 69, -5] },
    // 4 (global 508) — 7 of 11, 1 way, 44 near-misses
    { weights: [44, 64, -6, 50, 77, 60, -6, -38, -6, 84, -14], locked: [7], maxWeights: 7 },
    // 5 (global 509) — 6 of 10, 1 way, 58 near-misses
    { weights: [-19, 24, -24, 95, 87, -32, -6, -40, 27, 14] },
    // 6 (global 510) — 6 of 11, 2 ways, 60 near-misses
    { weights: [-35, 82, -20, 74, 50, -12, -44, 47, 36, 89, -20] },
    // 7 (global 511) — 7 of 11, 1 way, 48 near-misses
    { weights: [98, -39, 72, -12, 21, -33, 24, -12, -33, 78, 98], maxWeights: 7 },
    // 8 (global 512) — 7 of 11, 1 way, 40 near-misses
    { weights: [-31, -17, 73, -22, -25, 31, -17, 69, -45, -9, 97], locked: [9], maxWeights: 7 },
    // 9 (global 513) — 7 of 11, 3 ways, 55 near-misses
    { weights: [-11, -31, 95, 48, 21, -43, 96, -20, -20, 96, 96], maxWeights: 7 },
    // 10 (global 514) — 6 of 11, 5 ways, 64 near-misses
    { weights: [-27, 53, -14, 26, 69, -11, 19, -39, 69, 65, -15], maxWeights: 6 },
    // 11 (global 515) — 6 of 11, 4 ways, 70 near-misses
    { weights: [-41, -31, -25, 95, 83, 99, 86, -20, -25, -34, -20] },
    // 12 (global 516) — 6 of 11, 4 ways, 68 near-misses
    { weights: [-22, 42, -38, 95, -8, -33, -9, -44, -5, 92, 92] },
    // 13 (global 517) — 6 of 11, 3 ways, 66 near-misses
    { weights: [-19, 64, -41, 55, 14, -15, -12, 81, 64, 19, -23], maxWeights: 6 },
    // 14 (global 518) — 7 of 11, 2 ways, 50 near-misses
    { weights: [75, -11, 79, -17, -43, -26, -17, -20, 96, 24, 96], maxWeights: 7 },
    // 15 (global 519) — 7 of 11, 2 ways, 43 near-misses
    { weights: [-19, -39, 99, -6, -25, -43, -18, -10, -31, 72, -39], maxWeights: 7 },
    // 16 (global 520) — 6 of 11, 2 ways, 76 near-misses
    { weights: [-40, 59, 79, -42, -32, 27, -41, -14, -23, 97, 32] },
    // 17 (global 521) — 7 of 12, 2 ways, 44 near-misses
    { weights: [95, 9, -8, -17, -33, -30, -35, 42, 95, -30, 11, -24], locked: [6], maxWeights: 7 },
    // 18 (global 522) — 7 of 12, 3 ways, 50 near-misses
    { weights: [9, 92, -14, -12, -39, 60, 94, -16, 78, -5, -35, 71], locked: [3], maxWeights: 7 },
    // 19 (global 523) — 6 of 11, 1 way, 63 near-misses
    { weights: [81, 94, -23, -6, -13, 47, 27, 32, 70, -15, -19] },
    // 20 (global 524) — 7 of 11, 3 ways, 74 near-misses
    { weights: [92, 92, -16, -33, 56, 92, -24, -4, -40, 17, -7] },
    // 21 (global 525) — 6 of 12, 4 ways, 52 near-misses
    { weights: [92, -39, 90, -42, 74, 94, 24, -11, -11, -33, -15, -19], locked: [8], maxWeights: 7 },
    // 22 (global 526) — 6 of 11, 2 ways, 56 near-misses
    { weights: [53, 98, -17, 20, 70, -5, -43, 71, -20, -22, -28], maxWeights: 6 },
    // 23 (global 527) — 7 of 12, 6 ways, 48 near-misses
    { weights: [-32, -42, -18, 86, -41, -21, -21, -12, 21, -4, 98, -35], locked: [1] },
    // 24 (global 528) — 7 of 12, 7 ways, 59 near-misses
    { weights: [-13, 85, -6, -31, 85, 95, -6, -10, 48, 78, 59, -10] },
  ],
}
