import type { LevelPack } from '../types'

/**
 * Cold Equations — The tray owes you nothing.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack18: LevelPack = {
  id: 'pack-18',
  name: 'Cold Equations',
  tagline: 'The tray owes you nothing.',
  levels: [
    // 1 (global 409) — 5 of 10, 1 way, 45 near-misses
    { weights: [89, 35, -8, -20, 64, -20, 41, -23, 56, -21] },
    // 2 (global 410) — 6 of 11, 1 way, 42 near-misses
    { weights: [74, 46, 66, 71, 70, -37, 9, -26, -9, -5, 94] },
    // 3 (global 411) — 6 of 10, 1 way, 36 near-misses
    { weights: [71, 52, -6, 88, -28, -17, 57, 94, -35, -23], maxWeights: 6 },
    // 4 (global 412) — 6 of 10, 1 way, 34 near-misses
    { weights: [99, -42, -11, 89, -13, -38, 99, -29, -40, 51], maxWeights: 6 },
    // 5 (global 413) — 6 of 11, 3 ways, 42 near-misses
    { weights: [88, 98, 18, -15, 94, -26, -42, -10, -42, 28, 95], maxWeights: 6 },
    // 6 (global 414) — 6 of 11, 3 ways, 42 near-misses
    { weights: [-22, 88, 58, -13, -4, 61, -10, -43, 64, 86, 76], maxWeights: 6 },
    // 7 (global 415) — 6 of 11, 1 way, 43 near-misses
    { weights: [-30, 98, 28, -44, 44, -42, 47, 99, 35, 86, -14] },
    // 8 (global 416) — 6 of 11, 1 way, 43 near-misses
    { weights: [-6, 45, 48, 39, 80, 66, 85, -33, -16, -29, 43] },
    // 9 (global 417) — 6 of 11, 1 way, 43 near-misses
    { weights: [35, -20, -39, 85, 39, 84, 50, -12, -30, 66, 84] },
    // 10 (global 418) — 6 of 11, 1 way, 38 near-misses
    { weights: [39, -6, 41, -41, 61, -25, -22, 68, 90, 93, 74], maxWeights: 6 },
    // 11 (global 419) — 6 of 11, 4 ways, 40 near-misses
    { weights: [-7, -5, 94, -34, -7, -43, 77, -38, 95, 68, 8], maxWeights: 6 },
    // 12 (global 420) — 6 of 10, 3 ways, 44 near-misses
    { weights: [-6, 58, -21, 79, -26, 70, -39, -19, -8, -9] },
    // 13 (global 421) — 6 of 10, 3 ways, 44 near-misses
    { weights: [35, -45, 71, 44, -5, 25, -20, -15, 78, -8], maxWeights: 6 },
    // 14 (global 422) — 6 of 10, 1 way, 40 near-misses
    { weights: [-33, 95, -18, 39, -42, 15, -12, -9, -36, 92] },
    // 15 (global 423) — 6 of 11, 2 ways, 42 near-misses
    { weights: [22, -17, 76, 69, 96, -26, 73, -17, -15, 69, 33], maxWeights: 6 },
    // 16 (global 424) — 6 of 11, 2 ways, 42 near-misses
    { weights: [77, -4, -38, 25, 65, -20, -13, 56, 50, 96, 36], maxWeights: 6 },
    // 17 (global 425) — 6 of 11, 1 way, 39 near-misses
    { weights: [55, 96, 80, -31, 55, -9, 58, -30, 20, 72, -17], maxWeights: 6 },
    // 18 (global 426) — 6 of 10, 2 ways, 44 near-misses
    { weights: [-8, -18, -32, -15, 31, 98, -41, 65, 8, -32] },
    // 19 (global 427) — 6 of 10, 2 ways, 39 near-misses
    { weights: [60, -6, 94, 21, 51, -12, -28, -45, -41, -6], maxWeights: 6 },
    // 20 (global 428) — 5 of 10, 1 way, 45 near-misses
    { weights: [91, -28, -42, -43, -20, -11, 74, -5, 42, 60] },
    // 21 (global 429) — 6 of 11, 2 ways, 37 near-misses
    { weights: [-4, -20, 84, 74, 95, -45, -29, -9, 65, -45, -40], locked: [8] },
    // 22 (global 430) — 6 of 11, 2 ways, 36 near-misses
    { weights: [-37, -31, -34, 61, 51, -42, -26, 96, 91, -34, -26], maxWeights: 6 },
    // 23 (global 431) — 6 of 11, 3 ways, 47 near-misses
    { weights: [79, 97, -40, -39, 22, 43, -44, -23, -21, 96, -21] },
    // 24 (global 432) — 6 of 11, 4 ways, 52 near-misses
    { weights: [45, 20, 31, -7, -5, 46, 69, 69, -18, 89, -18] },
  ],
}
