import type { LevelPack } from '../types'

/**
 * Crosswinds — Push and lift, all at once.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack5: LevelPack = {
  id: 'pack-5',
  name: 'Crosswinds',
  tagline: 'Push and lift, all at once.',
  levels: [
    // 1 (global 97) — 4 of 8, 2 ways, 21 near-misses
    { weights: [28, 55, -11, -21, 48, 21, 25, -5] },
    // 2 (global 98) — 4 of 9, 4 ways, 23 near-misses
    { weights: [21, 9, 28, 34, -18, 83, -26, 19, -14] },
    // 3 (global 99) — 4 of 8, 3 ways, 22 near-misses
    { weights: [-5, 68, 64, -31, 63, -32, 60, -29] },
    // 4 (global 100) — 4 of 8, 2 ways, 19 near-misses
    { weights: [-36, -32, -24, 69, -7, 37, 68, 58] },
    // 5 (global 101) — 4 of 8, 2 ways, 22 near-misses
    { weights: [-21, 35, 31, -15, -30, 48, 64, 20] },
    // 6 (global 102) — 4 of 8, 2 ways, 22 near-misses
    { weights: [28, 35, 23, -10, 23, 50, -8, -21] },
    // 7 (global 103) — 4 of 8, 2 ways, 22 near-misses
    { weights: [51, 25, -19, 69, 39, 18, -4, -19] },
    // 8 (global 104) — 4 of 8, 3 ways, 23 near-misses
    { weights: [-26, 69, -4, 64, -44, -22, 26, 28] },
    // 9 (global 105) — 4 of 8, 3 ways, 23 near-misses
    { weights: [19, 77, -8, -6, -9, 12, -16, 70] },
    // 10 (global 106) — 4 of 8, 1 way, 19 near-misses
    { weights: [41, 45, 29, 48, -4, -17, -6, 37] },
    // 11 (global 107) — 4 of 8, 1 way, 19 near-misses
    { weights: [-28, -13, 66, 25, 64, 21, -6, 20] },
    // 12 (global 108) — 4 of 8, 1 way, 19 near-misses
    { weights: [39, -40, -14, 43, 36, 41, -6, 85] },
    // 13 (global 109) — 4 of 8, 1 way, 19 near-misses
    { weights: [-30, -9, 12, -7, 27, 32, 72, 6] },
    // 14 (global 110) — 4 of 8, 1 way, 19 near-misses
    { weights: [63, -4, 68, 70, 68, 14, -13, -12] },
    // 15 (global 111) — 4 of 8, 2 ways, 20 near-misses
    { weights: [60, 11, -15, 78, -10, -5, -17, 8] },
    // 16 (global 112) — 4 of 8, 2 ways, 20 near-misses
    { weights: [11, -16, -7, -9, 20, 75, -9, 15] },
    // 17 (global 113) — 4 of 8, 2 ways, 20 near-misses
    { weights: [65, -4, -23, -22, 33, 60, 58, -27] },
    // 18 (global 114) — 4 of 8, 2 ways, 20 near-misses
    { weights: [88, -10, -19, -22, 93, -23, 12, 16] },
    // 19 (global 115) — 4 of 9, 4 ways, 25 near-misses
    { weights: [86, -33, -20, 86, 34, 25, 37, 27, -24] },
    // 20 (global 116) — 4 of 8, 1 way, 20 near-misses
    { weights: [-5, 17, 52, 32, -9, 46, -12, 34] },
    // 21 (global 117) — 4 of 8, 1 way, 20 near-misses
    { weights: [-41, -25, 24, 7, 70, 40, 63, -46] },
    // 22 (global 118) — 4 of 8, 1 way, 20 near-misses
    { weights: [9, 77, -21, 69, -15, -17, 22, 16] },
    // 23 (global 119) — 4 of 8, 2 ways, 21 near-misses
    { weights: [72, 79, 79, 35, -43, -35, -9, -38] },
    // 24 (global 120) — 4 of 9, 4 ways, 23 near-misses
    { weights: [22, -9, 11, -12, 94, 26, -41, -36, 17] },
  ],
}
