import type { LevelPack } from '../types'

/**
 * Updraft — Let go and let it climb.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack13: LevelPack = {
  id: 'pack-13',
  name: 'Updraft',
  tagline: 'Let go and let it climb.',
  levels: [
    // 1 (global 289) — 5 of 10, 4 ways, 33 near-misses
    { weights: [-4, -43, -39, 91, 93, -42, -32, 66, 53, -41] },
    // 2 (global 290) — 5 of 10, 4 ways, 38 near-misses
    { weights: [51, 73, -41, -18, -11, 7, -31, 51, 41, 77] },
    // 3 (global 291) — 6 of 10, 3 ways, 34 near-misses
    { weights: [-44, 75, 62, 15, -44, 10, -34, -9, 99, 99] },
    // 4 (global 292) — 5 of 9, 1 way, 33 near-misses
    { weights: [-21, 34, -13, 52, -33, -4, 17, 17, 82] },
    // 5 (global 293) — 5 of 10, 4 ways, 36 near-misses
    { weights: [77, -36, 46, 76, -28, -32, 70, -16, 71, -31] },
    // 6 (global 294) — 6 of 10, 4 ways, 32 near-misses
    { weights: [76, 74, -4, -30, 89, -29, 9, -15, -34, 75] },
    // 7 (global 295) — 5 of 9, 1 way, 34 near-misses
    { weights: [-8, 8, 88, -34, -45, -14, 28, 34, 35] },
    // 8 (global 296) — 5 of 10, 4 ways, 32 near-misses
    { weights: [-7, -31, 94, -34, -34, -34, 52, 82, 87, 42], maxWeights: 5 },
    // 9 (global 297) — 5 of 9, 1 way, 32 near-misses
    { weights: [94, -13, -35, -16, -37, 22, 42, 71, -16] },
    // 10 (global 298) — 5 of 10, 4 ways, 29 near-misses
    { weights: [-13, -33, -26, 75, 64, -9, -37, 71, -10, -21], locked: [3] },
    // 11 (global 299) — 6 of 10, 4 ways, 36 near-misses
    { weights: [23, 82, 23, -4, 45, 77, -44, -35, -23, 91] },
    // 12 (global 300) — 5 of 10, 2 ways, 37 near-misses
    { weights: [39, 42, -8, 55, -23, -11, 64, 74, -43, 45] },
    // 13 (global 301) — 5 of 10, 4 ways, 31 near-misses
    { weights: [87, -13, -16, 42, -31, 66, 60, -16, -17, -33], maxWeights: 5 },
    // 14 (global 302) — 5 of 9, 1 way, 31 near-misses
    { weights: [-15, 55, 78, -35, 48, -8, -42, -5, -12] },
    // 15 (global 303) — 5 of 10, 3 ways, 34 near-misses
    { weights: [62, -44, -22, 78, -39, -30, 70, -18, -24, -4] },
    // 16 (global 304) — 5 of 10, 4 ways, 34 near-misses
    { weights: [-11, -40, -21, 82, 79, -43, -13, 50, 82, 59], maxWeights: 5 },
    // 17 (global 305) — 6 of 10, 2 ways, 34 near-misses
    { weights: [90, 46, 53, -12, -5, -42, 51, 62, 29, -26] },
    // 18 (global 306) — 5 of 9, 1 way, 29 near-misses
    { weights: [75, -40, 65, 44, -6, 37, -32, -11, -4], maxWeights: 5 },
    // 19 (global 307) — 5 of 10, 2 ways, 31 near-misses
    { weights: [-24, -43, 52, 57, 8, -25, -10, 73, -22, 86], maxWeights: 5 },
    // 20 (global 308) — 5 of 10, 2 ways, 31 near-misses
    { weights: [-29, 79, -6, 75, -5, 93, 28, -24, -44, 46], maxWeights: 5 },
    // 21 (global 309) — 5 of 10, 2 ways, 41 near-misses
    { weights: [63, 91, 71, 23, -25, -40, 35, 71, 7, -30] },
    // 22 (global 310) — 5 of 10, 3 ways, 37 near-misses
    { weights: [-44, -30, -28, 91, 72, 85, -27, -28, 81, -21] },
    // 23 (global 311) — 6 of 10, 4 ways, 33 near-misses
    { weights: [-45, -39, -41, -35, 96, -25, -5, 77, 94, 87] },
    // 24 (global 312) — 5 of 10, 2 ways, 34 near-misses
    { weights: [-7, 72, -44, -42, -41, 85, -30, 61, -43, 22] },
  ],
}
