import type { LevelPack } from '../types'

/**
 * Locked In — Some weights are not going anywhere.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack6: LevelPack = {
  id: 'pack-6',
  name: 'Locked In',
  tagline: 'Some weights are not going anywhere.',
  levels: [
    // 1 (global 121) — 4 of 9, 1 way, 22 near-misses
    { weights: [-28, 92, -35, 34, -26, 92, 73, 32, 94] },
    // 2 (global 122) — 4 of 9, 1 way, 21 near-misses
    { weights: [-17, 25, 9, 66, -41, -38, 57, -42, 93] },
    // 3 (global 123) — 4 of 9, 1 way, 25 near-misses
    { weights: [-21, 56, 37, -10, 72, -41, 62, 8, -6] },
    // 4 (global 124) — 4 of 9, 3 ways, 21 near-misses
    { weights: [-25, -5, -25, 65, 32, 91, 30, 25, -17] },
    // 5 (global 125) — 4 of 9, 4 ways, 26 near-misses
    { weights: [14, -8, 90, -36, 21, -24, 80, 34, -25] },
    // 6 (global 126) — 4 of 9, 4 ways, 21 near-misses
    { weights: [91, -26, -46, -44, 68, 58, -15, -23, 48] },
    // 7 (global 127) — 4 of 9, 2 ways, 21 near-misses
    { weights: [68, 45, -9, 25, -9, 10, 64, 63, -12] },
    // 8 (global 128) — 4 of 9, 2 ways, 23 near-misses
    { weights: [-38, 66, 28, 95, -7, 13, 22, 43, -34] },
    // 9 (global 129) — 4 of 9, 3 ways, 22 near-misses
    { weights: [28, -8, -29, 72, -45, 32, 15, 42, 57] },
    // 10 (global 130) — 5 of 9, 2 ways, 23 near-misses
    { weights: [23, -21, -16, 89, -12, 57, 34, 37, -42] },
    // 11 (global 131) — 5 of 9, 4 ways, 29 near-misses
    { weights: [-14, 84, -11, 68, 6, -21, 32, -8, -20] },
    // 12 (global 132) — 5 of 9, 1 way, 23 near-misses
    { weights: [-13, -26, 30, 99, -28, 18, -46, -5, -17] },
    // 13 (global 133) — 5 of 9, 2 ways, 23 near-misses
    { weights: [63, -9, 62, -20, -41, 75, -15, 11, 59] },
    // 14 (global 134) — 5 of 9, 1 way, 30 near-misses
    { weights: [15, 31, -14, -17, -11, 26, -17, 97, -41] },
    // 15 (global 135) — 5 of 9, 3 ways, 21 near-misses
    { weights: [99, -25, 9, -39, -12, 80, 50, -8, -4] },
    // 16 (global 136) — 5 of 9, 1 way, 22 near-misses
    { weights: [-44, 82, -12, -23, -36, 51, 76, -23, -10] },
    // 17 (global 137) — 5 of 9, 2 ways, 22 near-misses
    { weights: [-16, -31, 13, -42, -18, 77, 81, -12, 12] },
    // 18 (global 138) — 5 of 9, 2 ways, 28 near-misses
    { weights: [28, 57, 42, -33, -22, 63, -30, -4, 95] },
    // 19 (global 139) — 5 of 9, 3 ways, 24 near-misses
    { weights: [68, 13, -9, -10, 43, 66, -25, 25, -25] },
    // 20 (global 140) — 5 of 9, 2 ways, 25 near-misses
    { weights: [84, 43, 30, 31, -27, -9, -12, 31, 12] },
    // 21 (global 141) — 5 of 9, 2 ways, 22 near-misses
    { weights: [-17, -24, -28, 54, 92, 82, -16, -35, -19] },
    // 22 (global 142) — 5 of 9, 2 ways, 26 near-misses
    { weights: [-25, 53, 81, 17, -7, -16, 54, -44, -11] },
    // 23 (global 143) — 5 of 9, 1 way, 22 near-misses
    { weights: [-13, 10, -21, 62, 25, 68, 92, -34, -38] },
    // 24 (global 144) — 5 of 9, 3 ways, 23 near-misses
    { weights: [-28, -39, 19, -12, 65, 12, -9, 97, 20] },
  ],
}
