import type { LevelPack } from '../types'

/**
 * Terminal Velocity — All the way down, all the way back.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack23: LevelPack = {
  id: 'pack-23',
  name: 'Terminal Velocity',
  tagline: 'All the way down, all the way back.',
  levels: [
    // 1 (global 529) — 7 of 12, 1 way, 50 near-misses
    { weights: [-24, -17, 89, 90, 77, -30, 78, 78, 94, -25, 17, -8], maxWeights: 7 },
    // 2 (global 530) — 7 of 12, 4 ways, 46 near-misses
    { weights: [73, -13, 99, -35, 50, -44, -36, -10, 99, -40, -35, -4], locked: [6], maxWeights: 7 },
    // 3 (global 531) — 6 of 11, 4 ways, 62 near-misses
    { weights: [60, 75, -26, 92, -28, -28, 23, -10, 36, -28, -36], maxWeights: 6 },
    // 4 (global 532) — 6 of 11, 3 ways, 62 near-misses
    { weights: [-34, -17, 96, -21, -38, 11, -26, -5, -15, 34, -17] },
    // 5 (global 533) — 6 of 11, 4 ways, 86 near-misses
    { weights: [-4, 76, -37, 29, -29, 41, 73, -12, -37, -37, 41], maxWeights: 6 },
    // 6 (global 534) — 6 of 11, 4 ways, 78 near-misses
    { weights: [71, 89, -7, 31, -12, 25, -18, -24, -44, -7, 77], maxWeights: 6 },
    // 7 (global 535) — 7 of 11, 2 ways, 71 near-misses
    { weights: [51, 60, -14, -21, 63, -19, -5, 24, -19, 85, 53] },
    // 8 (global 536) — 6 of 11, 2 ways, 57 near-misses
    { weights: [-24, 20, -25, -22, 88, 15, -42, -5, -40, 95, 73], maxWeights: 6 },
    // 9 (global 537) — 7 of 12, 3 ways, 64 near-misses
    { weights: [-32, 84, -6, -19, -13, 96, -38, 96, -46, 96, 79, 94] },
    // 10 (global 538) — 7 of 12, 5 ways, 142 near-misses
    { weights: [99, -27, -8, -25, 72, 53, 51, -8, -26, 18, -36, 53] },
    // 11 (global 539) — 7 of 12, 3 ways, 76 near-misses
    { weights: [-35, 74, -15, 86, -26, 98, 46, 80, -21, -14, -8, 95] },
    // 12 (global 540) — 6 of 11, 1 way, 59 near-misses
    { weights: [-13, -26, 64, 31, 71, 64, 92, -5, 45, 25, -26], maxWeights: 6 },
    // 13 (global 541) — 7 of 12, 1 way, 51 near-misses
    { weights: [82, -4, 87, 12, -4, 70, -29, -25, 52, -8, 85, 82], maxWeights: 7 },
    // 14 (global 542) — 6 of 11, 2 ways, 61 near-misses
    { weights: [-37, -6, 50, 91, -7, -21, 33, 39, -7, 64, 58], maxWeights: 6 },
    // 15 (global 543) — 6 of 11, 2 ways, 63 near-misses
    { weights: [-33, 80, -24, 33, 71, -16, 9, 30, -11, 80, -38], maxWeights: 6 },
    // 16 (global 544) — 6 of 11, 1 way, 57 near-misses
    { weights: [58, -31, -7, 45, 25, -33, -38, 97, 57, -25, 97], maxWeights: 6 },
    // 17 (global 545) — 7 of 12, 2 ways, 54 near-misses
    { weights: [-37, 71, -9, -19, -18, -43, 37, 99, -24, 71, 25, 99], locked: [10] },
    // 18 (global 546) — 6 of 12, 7 ways, 62 near-misses
    { weights: [73, -26, -9, 96, 91, -4, -36, 81, -22, -27, 81, 84], maxWeights: 7 },
    // 19 (global 547) — 7 of 12, 2 ways, 64 near-misses
    { weights: [-21, -34, 52, -23, -34, 71, 99, 54, 43, -19, 95, 99] },
    // 20 (global 548) — 6 of 12, 6 ways, 86 near-misses
    { weights: [-13, 78, 78, -8, 76, 79, -42, 96, 32, -13, -13, -26], maxWeights: 7 },
    // 21 (global 549) — 6 of 11, 1 way, 55 near-misses
    { weights: [79, -36, -11, -30, 92, -34, -26, 74, -10, 7, 79], maxWeights: 6 },
    // 22 (global 550) — 7 of 11, 3 ways, 55 near-misses
    { weights: [94, -32, -7, -18, -11, -15, -7, -32, 65, -14, -41] },
    // 23 (global 551) — 6 of 11, 2 ways, 56 near-misses
    { weights: [78, 82, -35, 40, 99, -40, -28, -24, -14, -43, -7], maxWeights: 6 },
    // 24 (global 552) — 6 of 11, 2 ways, 56 near-misses
    { weights: [-22, 80, -46, 76, -41, -19, -7, -8, 68, 76, -34], maxWeights: 6 },
  ],
}
