import type { LevelPack } from '../types'

/**
 * Threadneedle — The way through is narrow.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack19: LevelPack = {
  id: 'pack-19',
  name: 'Threadneedle',
  tagline: 'The way through is narrow.',
  levels: [
    // 1 (global 433) — 6 of 11, 1 way, 38 near-misses
    { weights: [83, -25, 95, -14, 87, -33, 85, -26, 62, -30, 32], maxWeights: 6 },
    // 2 (global 434) — 6 of 11, 2 ways, 39 near-misses
    { weights: [88, -33, -14, -32, -16, 20, 92, 34, 14, -34, -17], maxWeights: 6 },
    // 3 (global 435) — 6 of 11, 3 ways, 50 near-misses
    { weights: [-17, -41, 51, 31, 90, 93, 90, -44, -18, 87, -14] },
    // 4 (global 436) — 6 of 11, 1 way, 41 near-misses
    { weights: [71, 75, -17, 39, 81, -5, -37, 75, 99, -44, 31], maxWeights: 6 },
    // 5 (global 437) — 6 of 10, 1 way, 40 near-misses
    { weights: [-44, -5, -15, 54, 84, -35, -18, 96, -20, -44] },
    // 6 (global 438) — 6 of 11, 2 ways, 47 near-misses
    { weights: [-43, 84, -29, -39, 89, 43, 93, -32, 66, 81, -7] },
    // 7 (global 439) — 6 of 11, 3 ways, 51 near-misses
    { weights: [-17, -32, 89, 32, 81, 82, 36, 94, -16, -39, -16] },
    // 8 (global 440) — 6 of 11, 3 ways, 51 near-misses
    { weights: [89, 57, -12, 90, 72, -9, -4, -38, 21, -8, 43] },
    // 9 (global 441) — 6 of 10, 1 way, 36 near-misses
    { weights: [-28, -15, -34, 96, -23, -20, -28, 72, 98, -34], maxWeights: 6 },
    // 10 (global 442) — 6 of 11, 2 ways, 48 near-misses
    { weights: [47, -14, 94, 53, -11, -20, 86, -28, -29, 70, 64] },
    // 11 (global 443) — 6 of 11, 4 ways, 44 near-misses
    { weights: [-25, -39, -13, 79, -32, 89, 6, -34, -23, -23, -33] },
    // 12 (global 444) — 6 of 10, 1 way, 39 near-misses
    { weights: [-17, -6, 92, -23, -37, 65, -22, 44, -44, 55], maxWeights: 6 },
    // 13 (global 445) — 6 of 10, 2 ways, 50 near-misses
    { weights: [93, -30, -17, 55, -23, 25, -25, 68, -30, 94] },
    // 14 (global 446) — 6 of 10, 1 way, 47 near-misses
    { weights: [41, 96, -25, 7, -33, 71, -6, -26, -16, 72] },
    // 15 (global 447) — 6 of 12, 6 ways, 51 near-misses
    { weights: [23, -31, 69, -30, 94, -6, 94, -28, -24, 92, 89, 93] },
    // 16 (global 448) — 7 of 12, 1 way, 37 near-misses
    { weights: [-15, 62, 94, -10, 98, 93, -19, 98, 94, -43, 38, -42], locked: [6] },
    // 17 (global 449) — 6 of 11, 1 way, 41 near-misses
    { weights: [-18, 99, 74, -37, 93, -30, -34, 86, 28, 65, -40], maxWeights: 6 },
    // 18 (global 450) — 7 of 11, 1 way, 42 near-misses
    { weights: [77, -4, 60, -19, -24, 99, -15, 8, 85, -30, 73] },
    // 19 (global 451) — 7 of 12, 3 ways, 44 near-misses
    { weights: [95, 60, 95, 77, 8, -32, -21, -39, 79, 18, -5, -8], locked: [10] },
    // 20 (global 452) — 7 of 12, 6 ways, 42 near-misses
    { weights: [81, 77, -41, -17, 90, 86, -21, 94, 21, -8, -8, -22], locked: [6] },
    // 21 (global 453) — 6 of 11, 4 ways, 46 near-misses
    { weights: [-36, -37, -36, -26, -29, 83, 14, -26, -18, -28, 92] },
    // 22 (global 454) — 6 of 11, 4 ways, 43 near-misses
    { weights: [-11, 87, -31, -15, -11, -18, 97, 69, -28, -29, -22], locked: [1] },
    // 23 (global 455) — 5 of 10, 1 way, 53 near-misses
    { weights: [76, 69, 63, -30, -13, -12, -18, 18, -24, 36] },
    // 24 (global 456) — 6 of 10, 2 ways, 50 near-misses
    { weights: [76, -18, -29, 52, 23, -35, 99, -13, -4, -18] },
  ],
}
