import type { LevelPack } from '../types'

/**
 * Ballast — Carry the weight, then drop it.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack11: LevelPack = {
  id: 'pack-11',
  name: 'Ballast',
  tagline: 'Carry the weight, then drop it.',
  levels: [
    // 1 (global 241) — 5 of 9, 2 ways, 28 near-misses
    { weights: [-36, -44, 45, 71, -16, 53, -7, 63, -9] },
    // 2 (global 242) — 5 of 9, 3 ways, 29 near-misses
    { weights: [-21, 42, -8, -11, 71, 62, -5, -6, -28] },
    // 3 (global 243) — 5 of 9, 1 way, 25 near-misses
    { weights: [8, 79, -37, -32, 79, -16, -13, 27, -22] },
    // 4 (global 244) — 5 of 9, 2 ways, 26 near-misses
    { weights: [-30, -31, -6, 57, 57, -33, 76, 20, 79], maxWeights: 5 },
    // 5 (global 245) — 5 of 9, 2 ways, 31 near-misses
    { weights: [6, -5, 54, -5, 63, 24, 46, -23, -7] },
    // 6 (global 246) — 5 of 9, 2 ways, 31 near-misses
    { weights: [57, 14, 13, -6, -45, -6, 56, 80, -14] },
    // 7 (global 247) — 5 of 10, 4 ways, 33 near-misses
    { weights: [60, 87, -23, -31, 21, 70, -31, -26, 75, 27] },
    // 8 (global 248) — 5 of 10, 1 way, 29 near-misses
    { weights: [83, 42, 87, 36, 35, -22, -32, 37, -17, 51] },
    // 9 (global 249) — 5 of 9, 1 way, 28 near-misses
    { weights: [22, 22, 58, 65, -34, -39, 47, -15, -7] },
    // 10 (global 250) — 5 of 9, 1 way, 28 near-misses
    { weights: [-4, 7, 76, 32, 13, 92, -19, -24, -15] },
    // 11 (global 251) — 5 of 9, 1 way, 28 near-misses
    { weights: [56, 86, -33, -17, 17, 81, 54, -16, -23] },
    // 12 (global 252) — 5 of 9, 1 way, 28 near-misses
    { weights: [22, 6, -21, 55, -7, -25, 80, 42, -7] },
    // 13 (global 253) — 5 of 9, 1 way, 28 near-misses
    { weights: [22, 63, -40, 49, 32, -25, -22, 79, -13] },
    // 14 (global 254) — 5 of 10, 2 ways, 30 near-misses
    { weights: [45, -11, 46, -44, 93, 28, 52, -12, 89, -36] },
    // 15 (global 255) — 5 of 9, 2 ways, 29 near-misses
    { weights: [-9, -28, -4, 54, -9, 46, -38, 64, 11] },
    // 16 (global 256) — 5 of 9, 1 way, 26 near-misses
    { weights: [-18, 8, -4, 42, -23, -30, -6, 60, 72] },
    // 17 (global 257) — 5 of 9, 1 way, 26 near-misses
    { weights: [-4, -17, 69, 83, -13, -4, 52, -38, 55] },
    // 18 (global 258) — 5 of 9, 1 way, 26 near-misses
    { weights: [-34, -16, -8, -25, -21, 80, 49, 25, 15] },
    // 19 (global 259) — 5 of 10, 3 ways, 34 near-misses
    { weights: [87, -40, 65, -10, -26, 69, -22, 31, 27, 74] },
    // 20 (global 260) — 5 of 9, 1 way, 29 near-misses
    { weights: [-32, -25, 55, -5, 63, -15, 30, 56, 35] },
    // 21 (global 261) — 5 of 9, 1 way, 29 near-misses
    { weights: [-5, 29, 66, -24, -6, 70, -25, 13, 51] },
    // 22 (global 262) — 5 of 9, 2 ways, 30 near-misses
    { weights: [-24, -21, 87, -29, 53, 28, -16, -23, 52] },
    // 23 (global 263) — 5 of 9, 2 ways, 30 near-misses
    { weights: [89, -9, 8, 9, 69, -37, -15, -6, -6] },
    // 24 (global 264) — 5 of 9, 2 ways, 30 near-misses
    { weights: [-27, -27, 46, 22, -4, 29, -13, 81, -5] },
  ],
}
