import type { LevelPack } from '../types'

/**
 * Deep End — The numbers stop being friendly.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack8: LevelPack = {
  id: 'pack-8',
  name: 'Deep End',
  tagline: 'The numbers stop being friendly.',
  levels: [
    // 1 (global 169) — 5 of 9, 2 ways, 23 near-misses
    { weights: [72, -24, 9, 92, -44, 17, -6, -29, 11] },
    // 2 (global 170) — 5 of 9, 2 ways, 23 near-misses
    { weights: [12, 86, -41, 72, -23, -27, 35, -24, 13] },
    // 3 (global 171) — 5 of 9, 2 ways, 23 near-misses
    { weights: [-43, -16, 84, -4, 50, 50, 13, 89, -25] },
    // 4 (global 172) — 5 of 9, 3 ways, 27 near-misses
    { weights: [-31, 28, -37, 73, 66, -4, 8, 57, -37] },
    // 5 (global 173) — 5 of 9, 2 ways, 24 near-misses
    { weights: [61, -31, 11, -36, -10, -35, 70, 58, 74] },
    // 6 (global 174) — 5 of 9, 3 ways, 28 near-misses
    { weights: [28, 13, -6, 40, -20, 70, -17, -24, 66] },
    // 7 (global 175) — 5 of 9, 3 ways, 28 near-misses
    { weights: [-21, 50, -30, -25, 27, 89, 16, 69, -40] },
    // 8 (global 176) — 5 of 9, 3 ways, 28 near-misses
    { weights: [62, 15, 35, 6, -11, -5, 84, -29, -14] },
    // 9 (global 177) — 5 of 9, 3 ways, 28 near-misses
    { weights: [-12, 34, 70, 74, 16, -15, 34, -27, -38] },
    // 10 (global 178) — 4 of 9, 2 ways, 29 near-misses
    { weights: [-8, 43, -23, 60, 54, -22, 45, 19, -14] },
    // 11 (global 179) — 5 of 9, 2 ways, 25 near-misses
    { weights: [-31, 41, -19, 25, 46, 14, -17, -33, 93] },
    // 12 (global 180) — 5 of 9, 2 ways, 25 near-misses
    { weights: [32, 39, -14, -18, 17, -38, 65, 77, -5] },
    // 13 (global 181) — 5 of 9, 2 ways, 25 near-misses
    { weights: [-13, -25, -43, -20, 31, 45, 64, 84, 6] },
    // 14 (global 182) — 5 of 9, 2 ways, 25 near-misses
    { weights: [-5, 59, 9, 53, -30, -12, -27, 76, 34] },
    // 15 (global 183) — 5 of 9, 2 ways, 25 near-misses
    { weights: [-27, 44, -23, 89, -7, 16, -36, 33, 47] },
    // 16 (global 184) — 5 of 9, 3 ways, 26 near-misses
    { weights: [16, 10, 80, 43, -6, -25, -11, -8, -25] },
    // 17 (global 185) — 5 of 9, 3 ways, 26 near-misses
    { weights: [-16, -23, 81, 66, -10, -16, 43, 32, -7] },
    // 18 (global 186) — 5 of 9, 3 ways, 26 near-misses
    { weights: [-7, 12, -18, -8, 78, 43, -30, 69, -17] },
    // 19 (global 187) — 4 of 9, 2 ways, 27 near-misses
    { weights: [-29, 71, -33, -9, 39, 70, -23, -37, 63] },
    // 20 (global 188) — 5 of 9, 2 ways, 28 near-misses
    { weights: [-33, -13, 26, 37, 73, 56, 21, 35, -16] },
    // 21 (global 189) — 5 of 9, 3 ways, 24 near-misses
    { weights: [76, 63, -17, -6, -14, -33, -21, 64, -34] },
    // 22 (global 190) — 5 of 9, 1 way, 25 near-misses
    { weights: [-5, -30, 25, 92, 12, 31, -21, 18, 40] },
    // 23 (global 191) — 5 of 9, 1 way, 25 near-misses
    { weights: [-17, 16, -38, 56, -9, 52, 9, 79, 47] },
    // 24 (global 192) — 5 of 9, 2 ways, 26 near-misses
    { weights: [-7, 70, 17, 53, -16, -36, 8, -33, 85] },
  ],
}
