import type { LevelPack } from '../types'

/**
 * Mind Benders — One answer. Nothing else close.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack11: LevelPack = {
  id: 'pack-11',
  name: 'Mind Benders',
  tagline: 'One answer. Nothing else close.',
  levels: [
    // 1 (global 241) — 5 of 11, 4 ways, 31 near-misses
    { weights: [-32, -37, 83, 83, -37, -39, 26, 97, 32, -8, 38], maxWeights: 5 },
    // 2 (global 242) — 5 of 11, 4 ways, 32 near-misses
    { weights: [76, 98, 41, -42, 10, -27, 78, 88, -42, -40, 62], maxWeights: 5 },
    // 3 (global 243) — 5 of 11, 4 ways, 48 near-misses
    { weights: [-16, 45, -9, 78, 95, 77, 50, -37, 55, -25, -4] },
    // 4 (global 244) — 6 of 11, 2 ways, 53 near-misses
    { weights: [-36, -8, 95, -9, 92, 73, -36, -40, -10, 63, 46], maxWeights: 6 },
    // 5 (global 245) — 6 of 11, 3 ways, 35 near-misses
    { weights: [-6, 91, 63, 69, 55, -11, -29, -21, 24, -41, 86], locked: [9] },
    // 6 (global 246) — 6 of 11, 1 way, 44 near-misses
    { weights: [-25, 37, -25, 71, 79, -10, 75, -11, -17, 64, 73] },
    // 7 (global 247) — 6 of 11, 4 ways, 28 near-misses
    { weights: [83, -38, -31, -23, -19, -31, 74, 32, 51, 88, 95], locked: [5] },
    // 8 (global 248) — 6 of 11, 2 ways, 29 near-misses
    { weights: [-43, 89, 85, 60, 47, -29, 85, -8, -21, 83, 55] },
    // 9 (global 249) — 6 of 11, 4 ways, 79 near-misses
    { weights: [-9, 58, -8, 95, -21, -41, -41, -16, -13, 40, 24] },
    // 10 (global 250) — 6 of 11, 3 ways, 43 near-misses
    { weights: [32, 78, -10, -4, 96, -28, -21, 51, 85, 79, -10], maxWeights: 6 },
    // 11 (global 251) — 6 of 11, 4 ways, 44 near-misses
    { weights: [72, 32, -35, -34, 95, 99, -40, -13, 51, 97, -42] },
    // 12 (global 252) — 6 of 11, 3 ways, 38 near-misses
    { weights: [-36, 88, -19, 43, 6, -30, 88, 95, 7, -31, -38], locked: [1] },
    // 13 (global 253) — 6 of 11, 2 ways, 30 near-misses
    { weights: [98, -18, 64, 95, -38, 16, -41, 75, 16, -15, -21], maxWeights: 6 },
    // 14 (global 254) — 6 of 11, 4 ways, 31 near-misses
    { weights: [91, 6, -4, -34, -13, -9, 66, -36, -37, 96, 94], maxWeights: 6 },
    // 15 (global 255) — 6 of 11, 1 way, 32 near-misses
    { weights: [81, 79, 83, 98, -44, 90, -24, 35, -40, -4, -39], maxWeights: 6 },
    // 16 (global 256) — 6 of 11, 4 ways, 41 near-misses
    { weights: [70, -11, 11, -5, -24, 71, 79, -27, 93, -27, -41], locked: [7] },
    // 17 (global 257) — 6 of 11, 2 ways, 49 near-misses
    { weights: [79, 96, -14, -33, -35, 15, -16, -25, 84, -37, -35], maxWeights: 6 },
    // 18 (global 258) — 6 of 11, 2 ways, 35 near-misses
    { weights: [80, 89, -24, -41, -21, 85, -41, -6, 89, 74, 80], maxWeights: 6 },
    // 19 (global 259) — 6 of 11, 1 way, 42 near-misses
    { weights: [71, -9, -16, 93, 75, -29, 93, 11, 27, -25, 80], maxWeights: 6 },
    // 20 (global 260) — 6 of 11, 2 ways, 45 near-misses
    { weights: [-38, -19, -5, 17, -34, -23, 59, 40, 58, 23, 94], maxWeights: 6 },
    // 21 (global 261) — 6 of 11, 4 ways, 49 near-misses
    { weights: [-13, 77, 94, -32, -29, 92, 78, -31, 11, -29, -19] },
    // 22 (global 262) — 6 of 11, 3 ways, 54 near-misses
    { weights: [-19, 92, -40, 81, -23, 97, -29, 85, -10, -17, -38], maxWeights: 6 },
    // 23 (global 263) — 6 of 11, 2 ways, 32 near-misses
    { weights: [-41, 6, -11, -23, 83, 64, -17, 88, 68, 85, 91] },
    // 24 (global 264) — 6 of 11, 4 ways, 48 near-misses
    { weights: [47, 82, 8, -20, 94, 69, -4, 68, -32, 28, -40] },
  ],
}
