import type { LevelPack } from '../types'

/**
 * Sky High — Overshoot on purpose. Come back clean.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack7: LevelPack = {
  id: 'pack-7',
  name: 'Sky High',
  tagline: 'Overshoot on purpose. Come back clean.',
  levels: [
    // 1 (global 145) — 5 of 9, 1 way, 24 near-misses
    { weights: [-31, -6, 14, -36, 18, 92, 52, 45, -6], maxWeights: 5 },
    // 2 (global 146) — 5 of 9, 2 ways, 26 near-misses
    { weights: [6, -6, 76, -19, 63, 53, -35, 37, -18] },
    // 3 (global 147) — 5 of 9, 3 ways, 23 near-misses
    { weights: [92, 73, -28, -24, -11, 12, -22, -11, 38] },
    // 4 (global 148) — 5 of 9, 2 ways, 23 near-misses
    { weights: [27, -28, 11, -8, -36, -22, -37, 43, 96] },
    // 5 (global 149) — 5 of 9, 2 ways, 22 near-misses
    { weights: [-17, 66, -27, -41, -28, -40, -19, 88, 81] },
    // 6 (global 150) — 5 of 9, 2 ways, 24 near-misses
    { weights: [-4, -14, 50, -20, -23, 86, -32, -7, 77] },
    // 7 (global 151) — 5 of 9, 2 ways, 24 near-misses
    { weights: [6, 94, -6, 43, -25, -36, 76, -29, -38] },
    // 8 (global 152) — 5 of 9, 1 way, 23 near-misses
    { weights: [43, -22, 31, 50, 13, -45, -19, 92, -15] },
    // 9 (global 153) — 5 of 9, 1 way, 22 near-misses
    { weights: [14, -19, 63, 91, 47, -20, -14, -31, 69] },
    // 10 (global 154) — 5 of 9, 2 ways, 23 near-misses
    { weights: [71, -31, -36, 37, -26, 75, 96, 68, -42] },
    // 11 (global 155) — 5 of 9, 2 ways, 23 near-misses
    { weights: [-4, 60, -9, 44, 82, -29, 33, 44, -24] },
    // 12 (global 156) — 5 of 9, 1 way, 26 near-misses
    { weights: [28, -20, 48, 52, -14, 28, -22, 14, 71] },
    // 13 (global 157) — 5 of 9, 3 ways, 24 near-misses
    { weights: [-35, -10, 60, 21, 50, 18, 92, -16, -17] },
    // 14 (global 158) — 5 of 9, 3 ways, 24 near-misses
    { weights: [24, -10, 83, -18, 24, 55, -15, -43, 52] },
    // 15 (global 159) — 5 of 10, 3 ways, 24 near-misses
    { weights: [11, 76, -13, -11, 97, -16, 29, 10, 75, 52] },
    // 16 (global 160) — 5 of 10, 3 ways, 32 near-misses
    { weights: [84, -20, -38, 59, -11, -16, -35, 61, -34, -22] },
    // 17 (global 161) — 5 of 10, 3 ways, 26 near-misses
    { weights: [59, 72, -22, -7, -18, -22, 83, 64, 77, -44], maxWeights: 5 },
    // 18 (global 162) — 5 of 10, 3 ways, 29 near-misses
    { weights: [68, 12, -29, 89, -4, 68, 77, 31, -17, -23] },
    // 19 (global 163) — 5 of 10, 4 ways, 26 near-misses
    { weights: [-22, 71, 68, -16, -11, -19, -11, 24, -35, 48], maxWeights: 5 },
    // 20 (global 164) — 5 of 10, 2 ways, 25 near-misses
    { weights: [-15, 45, 42, -43, 34, 74, -4, 89, -10, -43], locked: [4] },
    // 21 (global 165) — 5 of 10, 4 ways, 30 near-misses
    { weights: [-13, -43, 59, 94, -41, -7, -31, 76, -19, -30] },
    // 22 (global 166) — 5 of 10, 1 way, 28 near-misses
    { weights: [84, -11, -33, 72, 49, -20, 25, 8, 47, -12], maxWeights: 5 },
    // 23 (global 167) — 5 of 10, 1 way, 31 near-misses
    { weights: [-21, 47, -12, 63, -8, 89, 63, 35, -24, 34], maxWeights: 5 },
    // 24 (global 168) — 5 of 10, 3 ways, 27 near-misses
    { weights: [64, -13, -35, -27, 64, 35, 61, 29, -21, -18], maxWeights: 5 },
  ],
}
