import type { LevelPack } from '../types'

/**
 * Tightrope — One slip either way.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack15: LevelPack = {
  id: 'pack-15',
  name: 'Tightrope',
  tagline: 'One slip either way.',
  levels: [
    // 1 (global 337) — 6 of 10, 4 ways, 33 near-misses
    { weights: [70, -9, -29, -9, -27, -33, -13, 92, -26, 18] },
    // 2 (global 338) — 6 of 10, 1 way, 34 near-misses
    { weights: [-8, 49, 66, 82, 64, -25, 86, 25, -42, -10] },
    // 3 (global 339) — 6 of 10, 3 ways, 36 near-misses
    { weights: [-22, -4, 64, 96, 45, -32, -36, 97, -37, -11] },
    // 4 (global 340) — 6 of 10, 4 ways, 36 near-misses
    { weights: [86, -38, -30, -21, -13, -34, -44, 69, 7, 96] },
    // 5 (global 341) — 5 of 10, 2 ways, 32 near-misses
    { weights: [58, -43, 86, -13, -5, 47, -22, -40, -17, 87], maxWeights: 5 },
    // 6 (global 342) — 5 of 10, 3 ways, 38 near-misses
    { weights: [-37, -31, 93, -18, -43, -31, 70, 62, -39, -6] },
    // 7 (global 343) — 6 of 10, 2 ways, 33 near-misses
    { weights: [-44, -29, 69, -26, -15, -29, 62, 87, 94, -14] },
    // 8 (global 344) — 6 of 11, 4 ways, 40 near-misses
    { weights: [95, 98, -41, -33, 34, -33, 68, 45, -8, 84, 36] },
    // 9 (global 345) — 5 of 10, 1 way, 29 near-misses
    { weights: [-40, 96, -33, 91, -25, -19, -41, 65, -17, 66], maxWeights: 5 },
    // 10 (global 346) — 6 of 10, 3 ways, 34 near-misses
    { weights: [-18, -11, -30, -45, 94, -4, -30, 26, -32, 69] },
    // 11 (global 347) — 6 of 10, 3 ways, 39 near-misses
    { weights: [52, -34, 34, 29, 77, -33, -17, -23, -20, 97] },
    // 12 (global 348) — 6 of 10, 2 ways, 31 near-misses
    { weights: [-44, -28, 68, 84, -34, 91, 13, -32, 97, -27], maxWeights: 6 },
    // 13 (global 349) — 6 of 10, 2 ways, 36 near-misses
    { weights: [-39, 81, 66, -39, 91, 97, -17, -21, -26, 10] },
    // 14 (global 350) — 6 of 11, 4 ways, 38 near-misses
    { weights: [-32, 98, 34, -36, -23, 93, 87, 81, 82, -21, -35] },
    // 15 (global 351) — 6 of 10, 4 ways, 37 near-misses
    { weights: [-21, 73, 81, -9, 80, -33, -21, -26, -23, 75] },
    // 16 (global 352) — 5 of 10, 4 ways, 44 near-misses
    { weights: [28, 60, -17, 90, -27, -30, 26, 61, -39, -18] },
    // 17 (global 353) — 5 of 10, 1 way, 35 near-misses
    { weights: [-11, 41, -14, -20, 65, 68, -14, 8, 31, 21], maxWeights: 5 },
    // 18 (global 354) — 6 of 11, 2 ways, 38 near-misses
    { weights: [-11, 83, -20, 82, -14, -26, 34, 39, 55, 56, 94] },
    // 19 (global 355) — 5 of 10, 4 ways, 42 near-misses
    { weights: [29, -7, 66, 58, -19, -35, 87, -11, -44, -15] },
    // 20 (global 356) — 6 of 11, 3 ways, 39 near-misses
    { weights: [93, -18, 96, 89, 11, 66, -35, -20, -12, -18, 69] },
    // 21 (global 357) — 5 of 10, 1 way, 38 near-misses
    { weights: [-21, 95, 50, -37, 37, 60, -40, -11, -39, 63] },
    // 22 (global 358) — 6 of 10, 3 ways, 33 near-misses
    { weights: [99, -13, 68, 82, -40, -26, -18, -4, -21, 53], maxWeights: 6 },
    // 23 (global 359) — 6 of 10, 3 ways, 38 near-misses
    { weights: [-9, -4, -43, 59, -17, 85, -33, -13, 90, 44] },
    // 24 (global 360) — 6 of 10, 3 ways, 38 near-misses
    { weights: [12, -35, -22, -9, -44, 85, 87, -35, -25, 95] },
  ],
}
