import type { LevelPack } from '../types'

/**
 * Tight Budget — Fewer pieces. Same 67.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack5: LevelPack = {
  id: 'pack-5',
  name: 'Tight Budget',
  tagline: 'Fewer pieces. Same 67.',
  levels: [
    // 1 (global 97) — 4 of 8, 2 ways, 19 near-misses
    { weights: [57, 26, -26, 64, -4, 39, -28, 9] },
    // 2 (global 98) — 4 of 8, 2 ways, 20 near-misses
    { weights: [69, 47, -7, 49, -6, 19, 7, -44] },
    // 3 (global 99) — 4 of 8, 2 ways, 22 near-misses
    { weights: [-21, 35, 31, -15, -30, 48, 64, 20] },
    // 4 (global 100) — 4 of 8, 3 ways, 21 near-misses
    { weights: [74, -34, -6, -43, 44, 72, -42, 71] },
    // 5 (global 101) — 4 of 8, 3 ways, 21 near-misses
    { weights: [95, -5, -5, 74, -8, -13, 76, 9] },
    // 6 (global 102) — 4 of 9, 3 ways, 31 near-misses
    { weights: [37, -33, -9, 46, -31, -20, 38, 22, 59] },
    // 7 (global 103) — 4 of 9, 2 ways, 25 near-misses
    { weights: [81, 31, -26, 41, -23, 66, 47, -23, -35] },
    // 8 (global 104) — 4 of 9, 3 ways, 23 near-misses
    { weights: [-9, 78, -22, 49, 83, -20, 34, 13, -40] },
    // 9 (global 105) — 4 of 9, 1 way, 22 near-misses
    { weights: [62, -4, 24, 41, -43, -31, -35, -34, 70] },
    // 10 (global 106) — 4 of 9, 3 ways, 25 near-misses
    { weights: [71, -16, 78, -31, -32, 46, -18, -12, 51] },
    // 11 (global 107) — 4 of 9, 4 ways, 23 near-misses
    { weights: [83, -24, 29, 63, -20, -43, -21, -37, 68] },
    // 12 (global 108) — 4 of 9, 4 ways, 20 near-misses
    { weights: [-42, 17, -39, 78, 76, 70, -35, 37, -42] },
    // 13 (global 109) — 4 of 9, 3 ways, 20 near-misses
    { weights: [70, -32, -16, -23, 8, 58, 45, 35, 71] },
    // 14 (global 110) — 4 of 9, 1 way, 23 near-misses
    { weights: [50, -25, -19, 69, 78, 83, -25, -29, -33] },
    // 15 (global 111) — 4 of 9, 4 ways, 21 near-misses
    { weights: [-7, 68, -30, -30, 63, 15, -6, 72, 40] },
    // 16 (global 112) — 4 of 9, 2 ways, 20 near-misses
    { weights: [-43, 23, 34, 39, 26, -38, -13, 37, 92] },
    // 17 (global 113) — 4 of 9, 1 way, 22 near-misses
    { weights: [-26, 40, -44, 61, -27, 40, -12, 15, 45] },
    // 18 (global 114) — 4 of 9, 1 way, 22 near-misses
    { weights: [37, -12, 47, 9, 18, -5, 65, 82, -34] },
    // 19 (global 115) — 4 of 9, 1 way, 27 near-misses
    { weights: [-35, 26, 58, 46, -36, 62, -29, 58, -12] },
    // 20 (global 116) — 4 of 9, 3 ways, 23 near-misses
    { weights: [75, -28, 58, -13, 76, -44, -23, -30, 24] },
    // 21 (global 117) — 4 of 9, 2 ways, 24 near-misses
    { weights: [62, -41, 7, 69, 51, 71, -21, -14, 20] },
    // 22 (global 118) — 4 of 9, 2 ways, 20 near-misses
    { weights: [-32, -7, 19, 82, 39, -35, 38, 57, -27] },
    // 23 (global 119) — 4 of 9, 3 ways, 28 near-misses
    { weights: [-10, 42, -44, 32, 47, -9, -17, 78, 11] },
    // 24 (global 120) — 4 of 9, 4 ways, 29 near-misses
    { weights: [92, 91, -41, -27, 37, 39, -29, 40, -34] },
  ],
}
