import type { LevelPack } from '../types'

/**
 * The Squeeze — No room left to be wrong.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack10: LevelPack = {
  id: 'pack-10',
  name: 'The Squeeze',
  tagline: 'No room left to be wrong.',
  levels: [
    // 1 (global 217) — 5 of 11, 2 ways, 45 near-misses
    { weights: [59, 82, 73, 39, -30, 50, -14, 41, -5, -7, -7], maxWeights: 5 },
    // 2 (global 218) — 5 of 11, 3 ways, 37 near-misses
    { weights: [-17, 64, -43, -5, 82, -27, 14, 77, 68, 87, 71] },
    // 3 (global 219) — 5 of 11, 5 ways, 37 near-misses
    { weights: [81, 80, -6, -18, 51, -19, -27, 68, 64, -41, 15], maxWeights: 5 },
    // 4 (global 220) — 5 of 11, 5 ways, 35 near-misses
    { weights: [53, -42, -42, -7, 94, 54, 70, -31, 77, 85, 41] },
    // 5 (global 221) — 5 of 11, 3 ways, 26 near-misses
    { weights: [-35, 46, 12, -19, 69, 53, -9, 92, 8, -30, 61], locked: [5] },
    // 6 (global 222) — 5 of 11, 2 ways, 64 near-misses
    { weights: [24, 49, -36, 61, 87, -29, 46, -12, 95, -5, -10] },
    // 7 (global 223) — 5 of 11, 2 ways, 40 near-misses
    { weights: [-36, 78, -8, -31, 17, -42, -22, -14, 65, 78, 74], locked: [1] },
    // 8 (global 224) — 5 of 11, 2 ways, 51 near-misses
    { weights: [12, -11, 12, 69, 92, -27, 87, -19, -17, -34, 35], maxWeights: 5 },
    // 9 (global 225) — 5 of 11, 4 ways, 36 near-misses
    { weights: [-14, -16, -19, 55, -15, 6, 87, 62, -28, -43, -40], locked: [1] },
    // 10 (global 226) — 5 of 11, 2 ways, 42 near-misses
    { weights: [-14, 37, 21, -31, -33, 78, 66, 39, -12, 69, -42], maxWeights: 5 },
    // 11 (global 227) — 5 of 11, 1 way, 41 near-misses
    { weights: [72, 64, -11, 90, 81, -25, 70, -32, 44, 32, -32] },
    // 12 (global 228) — 5 of 11, 4 ways, 36 near-misses
    { weights: [11, -24, 69, 38, 74, 66, -26, 94, -36, 59, -36], maxWeights: 5 },
    // 13 (global 229) — 5 of 11, 1 way, 31 near-misses
    { weights: [-15, 77, 69, -26, 95, -30, -41, 33, -15, 33, 37], maxWeights: 5 },
    // 14 (global 230) — 5 of 11, 2 ways, 27 near-misses
    { weights: [-38, 84, -42, 46, 84, -11, -44, -38, 80, 13, 51], locked: [2] },
    // 15 (global 231) — 5 of 11, 4 ways, 57 near-misses
    { weights: [52, -7, 23, 13, 13, 82, 32, 75, -5, -19, 30] },
    // 16 (global 232) — 5 of 11, 3 ways, 32 near-misses
    { weights: [70, -10, 58, 58, -6, -25, 79, -25, -35, -44, 91], locked: [5] },
    // 17 (global 233) — 5 of 11, 4 ways, 56 near-misses
    { weights: [86, -44, -42, -40, 96, -5, 97, 70, -28, -46, 75] },
    // 18 (global 234) — 5 of 11, 4 ways, 44 near-misses
    { weights: [-46, 45, 38, -20, -24, -24, -20, 90, 32, -18, 24], locked: [5] },
    // 19 (global 235) — 5 of 11, 3 ways, 42 near-misses
    { weights: [-23, 74, 43, 53, -24, -24, 9, 83, 45, 42, -11], maxWeights: 5 },
    // 20 (global 236) — 5 of 11, 1 way, 38 near-misses
    { weights: [15, 46, 58, -38, -42, 46, 78, 88, -24, -8, -23], maxWeights: 5 },
    // 21 (global 237) — 5 of 11, 4 ways, 35 near-misses
    { weights: [-20, 85, 68, -10, 76, 78, -5, -22, -22, -36, 46], locked: [7] },
    // 22 (global 238) — 5 of 11, 3 ways, 41 near-misses
    { weights: [45, 75, -15, 84, 41, 8, 96, -18, 87, -32, -24] },
    // 23 (global 239) — 5 of 11, 2 ways, 47 near-misses
    { weights: [92, -15, 86, -44, 37, -15, -8, 54, 15, -14, 77], maxWeights: 5 },
    // 24 (global 240) — 5 of 11, 1 way, 38 near-misses
    { weights: [-43, 30, -8, -26, -28, 24, -10, -14, 58, 76, -12], maxWeights: 5 },
  ],
}
