import type { LevelPack } from '../types'

/**
 * Counterweight — Balance is a subtraction problem.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack14: LevelPack = {
  id: 'pack-14',
  name: 'Counterweight',
  tagline: 'Balance is a subtraction problem.',
  levels: [
    // 1 (global 313) — 5 of 10, 4 ways, 40 near-misses
    { weights: [82, 66, -37, -33, -24, 75, 32, 8, -20, -38] },
    // 2 (global 314) — 5 of 10, 1 way, 31 near-misses
    { weights: [-32, -18, 49, -32, 58, 66, 32, -12, 83, 25], maxWeights: 5 },
    // 3 (global 315) — 5 of 10, 1 way, 31 near-misses
    { weights: [49, 32, -7, -16, -4, 45, 47, 61, 63, -31], maxWeights: 5 },
    // 4 (global 316) — 5 of 10, 2 ways, 32 near-misses
    { weights: [48, 59, 75, -31, -33, 89, 63, -12, -26, -42], maxWeights: 5 },
    // 5 (global 317) — 5 of 10, 2 ways, 37 near-misses
    { weights: [-8, 92, 37, -23, 23, -26, -4, 95, 37, -14] },
    // 6 (global 318) — 6 of 10, 1 way, 32 near-misses
    { weights: [47, 10, 36, -38, -36, 99, -33, 33, 99, -24] },
    // 7 (global 319) — 6 of 11, 2 ways, 34 near-misses
    { weights: [70, -28, -13, 70, 81, 87, 82, 15, -42, -13, 82] },
    // 8 (global 320) — 5 of 10, 4 ways, 38 near-misses
    { weights: [-34, -24, 88, 55, -16, -4, -6, -8, 30, 80] },
    // 9 (global 321) — 5 of 10, 4 ways, 38 near-misses
    { weights: [77, -38, 20, 68, -33, -33, -28, -9, -36, 30] },
    // 10 (global 322) — 5 of 10, 4 ways, 38 near-misses
    { weights: [65, 10, -40, -41, 85, 78, -44, -7, -40, -15] },
    // 11 (global 323) — 6 of 10, 2 ways, 33 near-misses
    { weights: [95, 12, -39, -10, -36, -39, 12, 96, -26, 16] },
    // 12 (global 324) — 6 of 10, 2 ways, 33 near-misses
    { weights: [-30, 57, -18, 95, 91, 94, -34, -35, 57, -39] },
    // 13 (global 325) — 6 of 10, 3 ways, 39 near-misses
    { weights: [41, -43, 88, 55, -6, -31, 13, -38, 96, 89] },
    // 14 (global 326) — 5 of 9, 2 ways, 39 near-misses
    { weights: [54, -12, -20, -18, -13, 47, -5, 57, 49] },
    // 15 (global 327) — 5 of 10, 3 ways, 41 near-misses
    { weights: [-30, -11, -27, 92, 57, 93, 53, 18, -34, -41] },
    // 16 (global 328) — 5 of 10, 3 ways, 41 near-misses
    { weights: [66, -17, 97, -26, -9, 43, -15, 9, -41, 62] },
    // 17 (global 329) — 5 of 10, 4 ways, 36 near-misses
    { weights: [-4, -20, 73, -34, 78, -36, -28, -21, 68, -32] },
    // 18 (global 330) — 6 of 11, 3 ways, 38 near-misses
    { weights: [99, -29, 98, 62, -30, -28, 23, 81, 65, 65, -43] },
    // 19 (global 331) — 6 of 10, 4 ways, 32 near-misses
    { weights: [53, -34, -5, 65, -16, 95, -15, 66, 84, -16], maxWeights: 6 },
    // 20 (global 332) — 6 of 10, 3 ways, 37 near-misses
    { weights: [47, 17, -21, -26, -26, 45, 83, -6, -15, 90] },
    // 21 (global 333) — 5 of 10, 2 ways, 43 near-misses
    { weights: [54, -34, 49, -41, 8, 87, 9, 56, 96, -41] },
    // 22 (global 334) — 6 of 10, 1 way, 33 near-misses
    { weights: [54, 86, -16, 14, 44, -4, 11, -6, 92, -37] },
    // 23 (global 335) — 5 of 10, 4 ways, 39 near-misses
    { weights: [-14, 88, 47, 76, 75, -15, -20, -10, -23, -30] },
    // 24 (global 336) — 5 of 10, 3 ways, 42 near-misses
    { weights: [-5, 28, -31, 65, -5, 69, 45, -37, 86, -23] },
  ],
}
