import type { LevelPack } from '../types'

/**
 * Mind Benders — Nothing here is close to obvious.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack20: LevelPack = {
  id: 'pack-20',
  name: 'Mind Benders',
  tagline: 'Nothing here is close to obvious.',
  levels: [
    // 1 (global 457) — 6 of 11, 3 ways, 47 near-misses
    { weights: [-21, 89, -36, -43, -18, -34, 96, 74, 77, 58, -15], maxWeights: 6 },
    // 2 (global 458) — 6 of 10, 1 way, 47 near-misses
    { weights: [-43, -44, 57, -22, 77, -18, 35, -9, 78, -4] },
    // 3 (global 459) — 6 of 11, 4 ways, 55 near-misses
    { weights: [64, -8, 70, -24, -41, 42, -8, 96, 17, 97, -27] },
    // 4 (global 460) — 6 of 11, 3 ways, 55 near-misses
    { weights: [-13, 82, -27, -43, 43, 97, 44, 98, 78, -36, -36] },
    // 5 (global 461) — 7 of 12, 2 ways, 43 near-misses
    { weights: [15, -15, 84, 72, -6, 92, -30, 72, 37, -31, 64, -15], locked: [6] },
    // 6 (global 462) — 6 of 11, 2 ways, 52 near-misses
    { weights: [-6, -39, 62, 78, 32, -33, 66, 82, -26, 96, -6] },
    // 7 (global 463) — 6 of 11, 3 ways, 42 near-misses
    { weights: [95, 64, -29, -20, -27, -25, 31, -27, -4, -18, 20], locked: [0], maxWeights: 6 },
    // 8 (global 464) — 6 of 11, 4 ways, 43 near-misses
    { weights: [-21, 90, -38, 87, -30, -29, -5, 38, -17, -17, -34], maxWeights: 6 },
    // 9 (global 465) — 6 of 11, 4 ways, 48 near-misses
    { weights: [-23, -18, 72, -22, -27, 50, 76, 95, 93, -30, -13], maxWeights: 6 },
    // 10 (global 466) — 6 of 11, 1 way, 49 near-misses
    { weights: [-7, 90, -38, -19, -26, -17, 50, 80, 65, 95, 63] },
    // 11 (global 467) — 6 of 11, 2 ways, 50 near-misses
    { weights: [-15, 83, 16, 9, 86, -39, 18, -18, 86, 95, -42], maxWeights: 6 },
    // 12 (global 468) — 6 of 11, 4 ways, 54 near-misses
    { weights: [-46, 94, 79, 99, -46, -22, 81, -4, -35, -39, 68] },
    // 13 (global 469) — 7 of 12, 3 ways, 51 near-misses
    { weights: [-6, 50, 18, 90, -8, 70, 91, -14, -38, 94, -11, 94] },
    // 14 (global 470) — 6 of 11, 1 way, 50 near-misses
    { weights: [87, -34, 73, -40, 60, -9, 86, 95, -8, 9, -22] },
    // 15 (global 471) — 6 of 11, 4 ways, 51 near-misses
    { weights: [-7, 13, 38, -7, 33, -34, 47, -8, -12, 98, -21], locked: [3] },
    // 16 (global 472) — 6 of 11, 2 ways, 54 near-misses
    { weights: [-37, 93, 53, 25, 41, 98, -32, -12, -8, 44, -4] },
    // 17 (global 473) — 6 of 11, 4 ways, 50 near-misses
    { weights: [93, 60, 80, -11, -5, 79, -40, -14, -17, 90, -40], maxWeights: 6 },
    // 18 (global 474) — 6 of 11, 3 ways, 45 near-misses
    { weights: [-31, -13, -37, -45, -24, 97, 94, -11, -20, -4, 64], maxWeights: 6 },
    // 19 (global 475) — 6 of 11, 1 way, 46 near-misses
    { weights: [-23, -8, 58, 47, 47, -17, 96, 89, 85, -39, -11], maxWeights: 6 },
    // 20 (global 476) — 6 of 11, 1 way, 46 near-misses
    { weights: [88, -10, -5, 78, -34, -29, 71, 89, -44, 31, 58], maxWeights: 6 },
    // 21 (global 477) — 6 of 11, 1 way, 46 near-misses
    { weights: [96, 96, -26, 78, -27, 8, -40, 87, 28, -18, -5], maxWeights: 6 },
    // 22 (global 478) — 6 of 11, 2 ways, 47 near-misses
    { weights: [-29, -32, -35, -35, 51, 92, -29, 90, -17, 85, 37], maxWeights: 6 },
    // 23 (global 479) — 6 of 11, 1 way, 49 near-misses
    { weights: [47, -17, 99, -18, 33, 44, -26, -18, 65, 89, 9], maxWeights: 6 },
    // 24 (global 480) — 6 of 11, 1 way, 49 near-misses
    { weights: [-20, -6, 95, 56, 48, 34, 14, -33, 84, -6, 47], maxWeights: 6 },
  ],
}
