import type { LevelPack } from '../types'

/**
 * Fine Margins — Everything lands one off.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack7: LevelPack = {
  id: 'pack-7',
  name: 'Fine Margins',
  tagline: 'Everything lands one off.',
  levels: [
    // 1 (global 145) — 4 of 9, 2 ways, 22 near-misses
    { weights: [5, -11, 84, -9, 54, 35, -12, 85, -16] },
    // 2 (global 146) — 4 of 8, 2 ways, 26 near-misses
    { weights: [65, -4, 68, 69, 7, -4, 39, -39] },
    // 3 (global 147) — 4 of 9, 3 ways, 23 near-misses
    { weights: [-6, 44, -17, 59, -30, -22, 26, 36, -38] },
    // 4 (global 148) — 4 of 8, 2 ways, 24 near-misses
    { weights: [-18, 22, 74, -20, 17, -6, -4, 53] },
    // 5 (global 149) — 4 of 9, 1 way, 22 near-misses
    { weights: [7, 32, -27, -26, 39, 85, 53, 71, -9] },
    // 6 (global 150) — 4 of 9, 1 way, 22 near-misses
    { weights: [24, -16, 23, -6, 22, 82, 77, 69, -28] },
    // 7 (global 151) — 4 of 8, 2 ways, 22 near-misses
    { weights: [-29, 93, 27, -24, 8, -24, -4, -7] },
    // 8 (global 152) — 4 of 8, 1 way, 22 near-misses
    { weights: [-22, -6, -43, 48, 24, 72, 70, -8] },
    // 9 (global 153) — 4 of 8, 1 way, 22 near-misses
    { weights: [-25, 20, -12, -5, 7, -17, 90, 80] },
    // 10 (global 154) — 4 of 8, 2 ways, 26 near-misses
    { weights: [52, 35, -6, -15, -7, -5, 40, 40] },
    // 11 (global 155) — 5 of 9, 3 ways, 24 near-misses
    { weights: [-4, 15, 37, 65, 18, 92, -7, -32, -24] },
    // 12 (global 156) — 5 of 9, 3 ways, 24 near-misses
    { weights: [47, 26, -23, 39, 89, 58, -41, -16, -5] },
    // 13 (global 157) — 5 of 9, 3 ways, 24 near-misses
    { weights: [75, 82, 23, 50, -40, -39, 40, -12, -39] },
    // 14 (global 158) — 4 of 8, 1 way, 23 near-misses
    { weights: [42, 77, -41, -5, 6, -9, 73, -42] },
    // 15 (global 159) — 5 of 9, 3 ways, 27 near-misses
    { weights: [55, -9, 16, -12, 47, 68, 7, -27, 6] },
    // 16 (global 160) — 5 of 9, 3 ways, 25 near-misses
    { weights: [29, 10, 77, -42, 84, 35, -24, -8, -14] },
    // 17 (global 161) — 5 of 9, 3 ways, 25 near-misses
    { weights: [29, 19, 60, 75, -21, -11, -5, -30, 46] },
    // 18 (global 162) — 5 of 9, 3 ways, 25 near-misses
    { weights: [-23, 6, 13, 56, 38, -14, -14, 74, -17] },
    // 19 (global 163) — 5 of 9, 3 ways, 23 near-misses
    { weights: [-22, 20, -38, 51, -30, 87, -11, -22, 72] },
    // 20 (global 164) — 4 of 8, 1 way, 27 near-misses
    { weights: [-6, 37, 37, 35, -8, 77, 6, -8] },
    // 21 (global 165) — 5 of 9, 2 ways, 25 near-misses
    { weights: [-39, 70, 21, 52, -19, -4, 10, 53, 59] },
    // 22 (global 166) — 5 of 9, 2 ways, 25 near-misses
    { weights: [81, 29, 13, -26, 18, -12, 60, -36, 28] },
    // 23 (global 167) — 5 of 9, 4 ways, 26 near-misses
    { weights: [56, 8, 43, 46, -5, 56, -8, -29, -11] },
    // 24 (global 168) — 5 of 9, 4 ways, 26 near-misses
    { weights: [52, -34, 82, -18, -6, 44, 52, 22, -27] },
  ],
}
