import type { LevelPack } from '../types'

/**
 * Crosswinds — Push and lift, all at once.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack9: LevelPack = {
  id: 'pack-9',
  name: 'Crosswinds',
  tagline: 'Push and lift, all at once.',
  levels: [
    // 1 (global 193) — 5 of 10, 3 ways, 28 near-misses
    { weights: [-42, -13, -7, 38, -44, 70, 96, 40, 30, -13], maxWeights: 5 },
    // 2 (global 194) — 5 of 10, 3 ways, 38 near-misses
    { weights: [6, 14, 75, -13, -39, 55, 84, 48, 33, -40] },
    // 3 (global 195) — 5 of 10, 4 ways, 43 near-misses
    { weights: [-27, -24, -5, -15, 50, 51, 74, 62, -4, 60] },
    // 4 (global 196) — 5 of 10, 2 ways, 26 near-misses
    { weights: [84, -39, 19, -9, 88, -39, 26, 66, 54, 51] },
    // 5 (global 197) — 5 of 10, 3 ways, 48 near-misses
    { weights: [57, 25, 26, -36, 45, -5, -21, 45, -36, 87] },
    // 6 (global 198) — 5 of 10, 4 ways, 34 near-misses
    { weights: [-19, 78, -14, 83, 42, -24, 48, -17, -15, 73] },
    // 7 (global 199) — 5 of 10, 4 ways, 42 near-misses
    { weights: [-22, -15, 25, -30, -28, -13, 98, 46, 46, 32] },
    // 8 (global 200) — 5 of 10, 4 ways, 46 near-misses
    { weights: [-10, -37, 38, -46, 45, -19, -34, 88, 38, -10] },
    // 9 (global 201) — 5 of 10, 1 way, 25 near-misses
    { weights: [46, 83, -25, -25, -12, 84, -33, 48, 61, 14] },
    // 10 (global 202) — 5 of 10, 1 way, 25 near-misses
    { weights: [74, -32, -25, 87, 76, -13, 60, 66, 30, -22] },
    // 11 (global 203) — 5 of 10, 1 way, 37 near-misses
    { weights: [-14, 56, 20, -16, -4, 91, 66, 90, -42, -22] },
    // 12 (global 204) — 5 of 10, 2 ways, 38 near-misses
    { weights: [73, 28, -22, 63, -7, -23, 32, -9, 31, 77] },
    // 13 (global 205) — 5 of 10, 2 ways, 25 near-misses
    { weights: [-27, -23, -40, 22, -45, -28, 51, -12, 86, -20] },
    // 14 (global 206) — 5 of 10, 4 ways, 31 near-misses
    { weights: [-13, -14, -13, -13, 70, 96, 6, 13, -45, -8], maxWeights: 5 },
    // 15 (global 207) — 5 of 10, 4 ways, 27 near-misses
    { weights: [-36, 81, 72, 49, -22, 96, -28, 60, -25, -16], maxWeights: 5 },
    // 16 (global 208) — 5 of 10, 3 ways, 28 near-misses
    { weights: [-39, -4, 55, 74, 74, 87, -11, 60, -30, -19] },
    // 17 (global 209) — 5 of 10, 4 ways, 47 near-misses
    { weights: [-23, -43, 56, 55, 93, 15, -16, -22, -5, 10] },
    // 18 (global 210) — 5 of 10, 4 ways, 42 near-misses
    { weights: [-9, 6, 33, -15, -46, 88, -32, -10, -35, 31] },
    // 19 (global 211) — 5 of 10, 4 ways, 31 near-misses
    { weights: [-23, -27, 85, -28, 75, 57, 66, -5, -23, 55] },
    // 20 (global 212) — 5 of 10, 4 ways, 39 near-misses
    { weights: [79, -18, -45, -10, 49, -33, 75, -38, 57, -35] },
    // 21 (global 213) — 5 of 10, 2 ways, 41 near-misses
    { weights: [57, 54, -7, -9, -38, -42, -39, 98, -32, 77] },
    // 22 (global 214) — 5 of 10, 3 ways, 45 near-misses
    { weights: [49, -40, 55, 5, -10, -16, 16, -22, -10, 98] },
    // 23 (global 215) — 5 of 11, 2 ways, 50 near-misses
    { weights: [64, 94, 45, -38, -32, -15, 44, -23, -37, 57, -36], maxWeights: 5 },
    // 24 (global 216) — 5 of 11, 3 ways, 45 near-misses
    { weights: [-7, 22, 49, -27, -11, 6, 87, -8, 73, -46, -25], maxWeights: 5 },
  ],
}
