import type { LevelPack } from '../types'

/**
 * The Squeeze — No room left to be wrong.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack10: LevelPack = {
  id: 'pack-10',
  name: 'The Squeeze',
  tagline: 'No room left to be wrong.',
  levels: [
    // 1 (global 217) — 4 of 9, 3 ways, 39 near-misses
    { weights: [-13, 9, -7, 14, 55, -13, 78, 10, 7] },
    // 2 (global 218) — 5 of 9, 2 ways, 29 near-misses
    { weights: [-7, -11, 20, 55, -7, -25, 22, 55, 71] },
    // 3 (global 219) — 5 of 9, 2 ways, 29 near-misses
    { weights: [-20, 8, 30, 70, -15, -9, 78, -9, 64] },
    // 4 (global 220) — 5 of 10, 4 ways, 31 near-misses
    { weights: [96, 52, 86, -44, 14, 52, -15, -41, 21, -12] },
    // 5 (global 221) — 5 of 9, 1 way, 26 near-misses
    { weights: [54, -30, 50, 16, 88, 38, -6, -33, -32] },
    // 6 (global 222) — 5 of 9, 1 way, 26 near-misses
    { weights: [-13, -6, 11, 57, 30, -42, 83, -43, 72] },
    // 7 (global 223) — 5 of 9, 1 way, 26 near-misses
    { weights: [-5, -21, -43, 47, 92, 32, 8, 13, -8] },
    // 8 (global 224) — 5 of 10, 2 ways, 28 near-misses
    { weights: [-16, -20, 73, 92, 27, 94, -22, -16, 69, 28] },
    // 9 (global 225) — 5 of 9, 1 way, 24 near-misses
    { weights: [95, 49, -38, -25, 31, -43, -6, -33, 14] },
    // 10 (global 226) — 5 of 9, 1 way, 24 near-misses
    { weights: [24, -32, -8, -44, -14, 58, 93, 60, -14] },
    // 11 (global 227) — 5 of 9, 1 way, 29 near-misses
    { weights: [66, 64, -35, 30, -9, -19, 24, 9, 54] },
    // 12 (global 228) — 5 of 9, 2 ways, 30 near-misses
    { weights: [66, 43, 10, -19, 66, -29, 69, -22, -24] },
    // 13 (global 229) — 5 of 9, 2 ways, 25 near-misses
    { weights: [-16, -7, -14, 48, -21, 87, 70, -5, -43] },
    // 14 (global 230) — 5 of 9, 2 ways, 30 near-misses
    { weights: [-38, 71, 12, 37, 15, -23, -32, 74, -17] },
    // 15 (global 231) — 5 of 9, 2 ways, 30 near-misses
    { weights: [-14, 17, -31, 28, -28, 28, 86, -46, 54] },
    // 16 (global 232) — 5 of 9, 2 ways, 30 near-misses
    { weights: [-9, 63, -16, 55, 41, -25, -7, 52, 9] },
    // 17 (global 233) — 5 of 10, 4 ways, 32 near-misses
    { weights: [-25, -41, 42, 61, 68, 90, -22, -28, 17, 77] },
    // 18 (global 234) — 5 of 9, 4 ways, 31 near-misses
    { weights: [87, 43, 43, -44, -5, -41, 71, -21, -17] },
    // 19 (global 235) — 5 of 9, 3 ways, 31 near-misses
    { weights: [-27, -4, 46, 62, -28, -10, 61, -39, 74] },
    // 20 (global 236) — 5 of 10, 1 way, 28 near-misses
    { weights: [14, 83, -6, 93, 16, 13, 28, -11, 19, -25] },
    // 21 (global 237) — 5 of 9, 1 way, 27 near-misses
    { weights: [-14, 85, -15, 89, 16, -21, -9, 24, 59] },
    // 22 (global 238) — 5 of 9, 1 way, 27 near-misses
    { weights: [46, 7, -12, 94, 76, -31, -12, 37, -14] },
    // 23 (global 239) — 5 of 10, 2 ways, 29 near-misses
    { weights: [-37, -15, -27, 83, 64, -24, 69, 76, 69, 34] },
    // 24 (global 240) — 5 of 9, 2 ways, 28 near-misses
    { weights: [-41, -16, -9, 44, -12, 9, 85, -12, 43] },
  ],
}
