import type { LevelPack } from '../types'

/**
 * Grandmaster — Every piece has to earn its place.
 *
 * GENERATED by `tools/generate-levels.ts` (seeded, reproducible). Every level
 * here was verified with the real solver at generation time: it has an exact-67
 * solution, its minimal build is the intended one, and its solution count is
 * inside the band for this point in the ramp. Re-run the generator rather than
 * hand-editing, and never reorder — progress is keyed by global level number.
 */
export const pack24: LevelPack = {
  id: 'pack-24',
  name: 'Grandmaster',
  tagline: 'Every piece has to earn its place.',
  levels: [
    // 1 (global 553) — 7 of 12, 2 ways, 45 near-misses
    { weights: [-43, -10, 47, -23, 9, -28, -10, 93, -32, 88, -23, -46], locked: [5], maxWeights: 7 },
    // 2 (global 554) — 7 of 12, 3 ways, 77 near-misses
    { weights: [98, 91, -37, -17, -17, -4, 73, 63, -42, 16, 86, 33], maxWeights: 7 },
    // 3 (global 555) — 7 of 12, 1 way, 59 near-misses
    { weights: [61, -27, 80, 82, -12, -12, 27, 80, 70, -24, -5, 86] },
    // 4 (global 556) — 7 of 12, 2 ways, 49 near-misses
    { weights: [-19, -6, 90, -32, -39, -25, -6, 84, 25, 84, 56, -19], locked: [7], maxWeights: 7 },
    // 5 (global 557) — 7 of 12, 2 ways, 72 near-misses
    { weights: [76, 72, 78, -8, -4, -20, -17, 55, 55, -16, 85, -17] },
    // 6 (global 558) — 7 of 12, 2 ways, 81 near-misses
    { weights: [-18, 86, -12, 87, -25, 86, -25, -24, 86, 88, 88, -30] },
    // 7 (global 559) — 7 of 12, 6 ways, 50 near-misses
    { weights: [-5, 7, -30, -30, -35, 86, 99, -15, -33, 99, -31, -30], locked: [8], maxWeights: 7 },
    // 8 (global 560) — 7 of 12, 1 way, 51 near-misses
    { weights: [72, 34, 88, -14, 98, 77, 58, -24, 53, -29, -14, -38], locked: [9], maxWeights: 7 },
    // 9 (global 561) — 7 of 11, 3 ways, 75 near-misses
    { weights: [92, 77, -38, -29, -23, 6, -9, -9, -23, 98, 43], maxWeights: 7 },
    // 10 (global 562) — 7 of 12, 3 ways, 53 near-misses
    { weights: [92, -26, -21, 15, -16, -26, 42, -27, -22, 87, -22, 42], locked: [1], maxWeights: 7 },
    // 11 (global 563) — 7 of 12, 1 way, 55 near-misses
    { weights: [-17, -8, -5, 50, 71, 95, 54, -21, 94, 65, 86, -42], maxWeights: 7 },
    // 12 (global 564) — 7 of 12, 6 ways, 172 near-misses
    { weights: [87, 38, 44, -23, 98, -22, -23, -21, 27, -16, -34, 27], maxWeights: 7 },
    // 13 (global 565) — 7 of 12, 3 ways, 134 near-misses
    { weights: [-46, -8, 27, -39, 90, -39, 8, -10, 90, 46, -17, 61], maxWeights: 7 },
    // 14 (global 566) — 7 of 12, 4 ways, 107 near-misses
    { weights: [99, -6, 31, -16, 31, -17, 74, -37, 70, -35, 72, -8], maxWeights: 7 },
    // 15 (global 567) — 7 of 12, 3 ways, 83 near-misses
    { weights: [-31, 95, 23, 88, -27, -46, 31, -23, 95, -31, -11, 95], maxWeights: 7 },
    // 16 (global 568) — 7 of 12, 2 ways, 145 near-misses
    { weights: [-19, 88, -44, -30, 55, 99, -26, 55, -34, -26, 71, -11] },
    // 17 (global 569) — 7 of 12, 2 ways, 157 near-misses
    { weights: [10, -43, -45, -43, -8, 68, 97, -16, 71, -8, -26, 8] },
    // 18 (global 570) — 7 of 12, 3 ways, 95 near-misses
    { weights: [-33, -26, 85, -15, -26, 31, -41, 96, 31, -10, -15, 16], locked: [2] },
    // 19 (global 571) — 6 of 11, 1 way, 68 near-misses
    { weights: [-21, 21, -13, 71, -9, 94, -43, 44, 78, -44, -8], maxWeights: 6 },
    // 20 (global 572) — 7 of 11, 4 ways, 77 near-misses
    { weights: [-32, 49, -31, 6, -15, -11, 89, -32, -10, 94, -9], maxWeights: 7 },
    // 21 (global 573) — 7 of 11, 1 way, 56 near-misses
    { weights: [-21, -15, -30, 64, -39, -23, 94, 99, 99, -24, 83], maxWeights: 7 },
    // 22 (global 574) — 7 of 12, 4 ways, 58 near-misses
    { weights: [58, 12, 92, -24, 80, -7, 92, 19, -26, -24, -24, -36], locked: [3], maxWeights: 7 },
    // 23 (global 575) — 7 of 12, 1 way, 111 near-misses
    { weights: [-26, -44, 83, -5, 62, -36, -5, 84, -23, 57, 78, 70] },
    // 24 (global 576) — 7 of 12, 1 way, 225 near-misses
    { weights: [-13, 15, -13, 69, 70, -43, 27, 62, -20, -13, 63, -7] },
  ],
}
